In [9]:
import shutil

shutil.rmtree('/content/llmr-a2')

In [10]:
%cd /content

/content

In [11]:
!git clone --branch benchmarking-back https://github.com/Tulsani/llmr-a2.git

Cloning into 'llmr-a2'...
remote: Enumerating objects: 165, done.
remote: Counting objects: 100% (165/165), done.
remote: Compressing objects: 100% (112/112), done.
remote: Total 165 (delta 85), reused 127 (delta 47), pack-reused 0 (from 0)
Receiving objects: 100% (165/165), 116.63 KiB | 6.86 MiB/s, done.
Resolving deltas: 100% (85/85), done.

In [12]:
%cd llmr-a2/

/content/llmr-a2

In [13]:
!ls student

benchmarking_script.py		 flash_attention_titron.py
benchmark_jit_attention.py	 __init__.py
benchmark_pytorch_attention.py	 memory_profiling.py
flash_attention_backward.py	 mixed_precision_accumlation.py
flash_attention_benchmarking.py  mixed_precision_profiling.py
flash_attention_pytroch.py	 nsys_profile.py

In [4]:
!pip install uv

Collecting uv
  Downloading uv-0.10.9-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Downloading uv-0.10.9-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (23.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.4/23.4 MB 113.8 MB/s eta 0:00:00
Installing collected packages: uv
Successfully installed uv-0.10.9

In [5]:
!uv pip install -e .

Using Python 3.12.12 environment at: /usr
Resolved 75 packages in 433ms
Prepared 25 packages in 26.83s
Uninstalled 17 packages in 604ms
Installed 25 packages in 210ms
 + a1-basics==1.0.3 (from file:///content/llmr-a2/a1-basics)
 + einx==0.4.1
 + humanfriendly==10.0
 + jaxtyping==0.3.9
 - nvidia-cublas-cu12==12.8.4.1
 + nvidia-cublas-cu12==12.4.5.8
 - nvidia-cuda-cupti-cu12==12.8.90
 + nvidia-cuda-cupti-cu12==12.4.127
 - nvidia-cuda-nvrtc-cu12==12.8.93
 + nvidia-cuda-nvrtc-cu12==12.4.127
 - nvidia-cuda-runtime-cu12==12.8.90
 + nvidia-cuda-runtime-cu12==12.4.127
 - nvidia-cudnn-cu12==9.10.2.21
 + nvidia-cudnn-cu12==9.1.0.70
 - nvidia-cufft-cu12==11.3.3.83
 + nvidia-cufft-cu12==11.2.1.3
 - nvidia-curand-cu12==10.3.9.90
 + nvidia-curand-cu12==10.3.5.147
 - nvidia-cusolver-cu12==11.7.3.90
 + nvidia-cusolver-cu12==11.6.1.9
 - nvidia-cusparse-cu12==12.5.8.93
 + nvidia-cusparse-cu12==12.3.1.170
 - nvidia-cusparselt-cu12==0.7.1
 + nvidia-cusparselt-cu12==0.6.2
 - nvidia-nccl-cu12==2.27.5
 + nvidia-nccl-cu12==2.21.5
 - nvidia-nvjitlink-cu12==12.8.93
 + nvidia-nvjitlink-cu12==12.4.127
 - nvidia-nvtx-cu12==12.8.90
 + nvidia-nvtx-cu12==12.4.127
 - psutil==5.9.5
 + psutil==7.2.2
 + student==1.0.5 (from file:///content/llmr-a2)
 + submitit==1.5.4
 - sympy==1.14.0
 + sympy==1.13.1
 - torch==2.10.0+cu128
 + torch==2.6.0
 - triton==3.6.0
 + triton==3.2.0
 + ty==0.0.21
 + wadler-lindig==0.1.7

## Part 1 : **Bencmarking**

### Manual Runs Rest

In [9]:
!uv run python ./student/benchmarking_script.py \
    --size medium \
    --context_length 512 \
    --mode forward_backward

Using CPython 3.12.12 interpreter at: /usr/bin/python3
Creating virtual environment at: .venv
Installed 75 packages in 191ms

Building model
  Parameters: 423.2M


Results  [forward_backward | medium | ctx=512]
  Mean :   261.18 ms

In [10]:
!uv run python ./student/benchmarking_script.py \
    --size small \
    --context_length 512 \
    --mode forward_backward

Building model
  Parameters: 128.6M


Results  [forward_backward | small | ctx=512]
  Mean :   129.35 ms

In [11]:
!uv run python ./student/benchmarking_script.py \
    --size large \
    --context_length 512 \
    --mode forward_backward

Building model
  Parameters: 969.4M


Results  [forward_backward | large | ctx=512]
  Mean :   489.50 ms

In [13]:
!uv run python ./student/benchmarking_script.py \
    --size xl \
    --context_length 512 \
    --mode forward_backward

Building model
  Parameters: 1998.2M


Results  [forward_backward | xl | ctx=512]
  Mean :   899.77 ms

In [15]:
!uv run python ./student/benchmarking_script.py \
    --size 2.7B \
    --context_length 512 \
    --mode forward_backward

Building model
  Parameters: 3406.8M


Results  [forward_backward | 2.7B | ctx=512]
  Mean :  1285.49 ms

Forward Benchmarking

In [18]:
!uv run python ./student/benchmarking_script.py \
    --size 2.7B \
    --context_length 512 \
    --mode forward

Building model
  Parameters: 3406.8M


Results  [forward | 2.7B | ctx=512]
  Mean :   373.15 ms

In [19]:
!uv run python ./student/benchmarking_script.py \
    --size xl \
    --context_length 512 \
    --mode forward

Building model
  Parameters: 1998.2M


Results  [forward | xl | ctx=512]
  Mean :   286.88 ms

In [20]:
!uv run python ./student/benchmarking_script.py \
    --size large \
    --context_length 512 \
    --mode forward

Building model
  Parameters: 969.4M


Results  [forward | large | ctx=512]
  Mean :   161.64 ms

In [21]:
!uv run python ./student/benchmarking_script.py \
    --size medium \
    --context_length 512 \
    --mode forward

Building model
  Parameters: 423.2M


Results  [forward | medium | ctx=512]
  Mean :    91.52 ms

In [8]:
!uv run python ./student/benchmarking_script.py \
    --size small \
    --context_length 512 \
    --mode forward

Building model
/content/llmr-a2/.venv/lib/python3.12/site-packages/torch/cuda/__init__.py:235: UserWarning:
NVIDIA RTX PRO 6000 Blackwell Server Edition with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_70 sm_75 sm_80 sm_86 sm_90.
If you want to use the NVIDIA RTX PRO 6000 Blackwell Server Edition GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(
  Parameters: 128.6M

Traceback (most recent call last):
  File "/content/llmr-a2/./student/benchmarking_script.py", line 181, in <module>
    main()
  File "/content/llmr-a2/./student/benchmarking_script.py", line 164, in main
    x,y = random_batch(args)
          ^^^^^^^^^^^^^^^^^^
  File "/content/llmr-a2/./student/benchmarking_script.py", line 76, in random_batch
    x = torch.randint(
        ^^^^^^^^^^^^^^
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

### b) *part*

##### Mean Calc

In [9]:
import subprocess
import pandas as pd
import re

sizes = ["small", "medium", "large", "xl", "2.7B"]
modes = ["forward", "backward", "forward_backward"]

results = []

for size in sizes:
    for mode in modes:
        print(f"\nRunning {size} | {mode}")

        cmd = f"""
        uv run python ./student/benchmarking_script.py \
            --size {size} \
            --context_length 512 \
            --mode {mode} \
            --warmup_steps 5 \
            --n_steps 10
        """

        output = subprocess.check_output(cmd, shell=True, text=True)
        print(output)

        # extract time
        match = re.search(r"Mean\s*:\s*([\d\.]+)\s*ms", output)
        if match:
            time_ms = float(match.group(1))
            results.append({
                "size": size,
                "mode": mode,
                "mean_ms": time_ms
            })

df = pd.DataFrame(results)
df

Running small | forward

Building model
  Parameters: 128.6M

Warm up steps being used

Results  [forward | small | ctx=512]
  Mean :    45.00 ms


Running small | backward

Building model
  Parameters: 128.6M

Warm up steps being used

Results  [backward | small | ctx=512]
  Mean :    90.94 ms


Running small | forward_backward

Building model
  Parameters: 128.6M

Warm up steps being used

Results  [forward_backward | small | ctx=512]
  Mean :   148.64 ms


Running medium | forward

Building model
  Parameters: 423.2M

Warm up steps being used

Results  [forward | medium | ctx=512]
  Mean :   134.16 ms


Running medium | backward

Building model
  Parameters: 423.2M

Warm up steps being used

Results  [backward | medium | ctx=512]
  Mean :   274.57 ms


Running medium | forward_backward

Building model
  Parameters: 423.2M

Warm up steps being used

Results  [forward_backward | medium | ctx=512]
  Mean :   446.26 ms


Running large | forward

Building model
  Parameters: 969.4M

Warm up steps being used

Results  [forward | large | ctx=512]
  Mean :   278.93 ms


Running large | backward

Building model
  Parameters: 969.4M

Warm up steps being used

Results  [backward | large | ctx=512]
  Mean :   589.73 ms


Running large | forward_backward

Building model
  Parameters: 969.4M

Warm up steps being used

Results  [forward_backward | large | ctx=512]
  Mean :   957.87 ms


Running xl | forward

Building model
  Parameters: 1998.2M

Warm up steps being used

Results  [forward | xl | ctx=512]
  Mean :   561.76 ms


Running xl | backward

Building model
  Parameters: 1998.2M

Warm up steps being used

Results  [backward | xl | ctx=512]
  Mean :  1158.90 ms


Running xl | forward_backward

Building model
  Parameters: 1998.2M

Warm up steps being used

Results  [forward_backward | xl | ctx=512]
  Mean :  1893.69 ms


Running 2.7B | forward

Building model
  Parameters: 3406.8M

Warm up steps being used

Results  [forward | 2.7B | ctx=512]
  Mean :   841.03 ms


Running 2.7B | backward

Building model
  Parameters: 3406.8M

Warm up steps being used

Results  [backward | 2.7B | ctx=512]
  Mean :  1733.57 ms


Running 2.7B | forward_backward

Building model
  Parameters: 3406.8M

Warm up steps being used

Results  [forward_backward | 2.7B | ctx=512]
  Mean :  2865.17 ms

      size              mode  mean_ms
0    small           forward    45.00
1    small          backward    90.94
2    small  forward_backward   148.64
3   medium           forward   134.16
4   medium          backward   274.57
5   medium  forward_backward   446.26
6    large           forward   278.93
7    large          backward   589.73
8    large  forward_backward   957.87
9       xl           forward   561.76
10      xl          backward  1158.90
11      xl  forward_backward  1893.69
12    2.7B           forward   841.03
13    2.7B          backward  1733.57
14    2.7B  forward_backward  2865.17

Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.
Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.
Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.

#### STD + Mean Cacl

In [6]:
import subprocess
import pandas as pd
import re

sizes = ["small", "medium", "large", "xl", "2.7B"]
modes = ["forward", "backward", "forward_backward"]

results = []

for size in sizes:
    for mode in modes:
        print(f"\nRunning {size} | {mode}")

        cmd = f"""
        uv run python ./student/benchmarking_script.py \
            --size {size} \
            --context_length 512 \
            --mode {mode} \
            --warmup_steps 5 \
            --n_steps 10
        """

        output = subprocess.check_output(cmd, shell=True, text=True)
        print(output)

        # extract time
        match = re.search(r"Mean\s*:\s*([\d\.]+)\s*ms", output)
        if match:
            time_ms = float(match.group(1))
            results.append({
                "size": size,
                "mode": mode,
                "mean_ms": time_ms
            })

df = pd.DataFrame(results)
df

Running small | forward

Building model
  Parameters: 128.6M

  Warming up for 5 step(s)...

Results  [forward | small | ctx=512]
  Mean :    45.04 ms
  Std  :     0.13 ms



Running small | backward

Building model
  Parameters: 128.6M

  Warming up for 5 step(s)...

Results  [backward | small | ctx=512]
  Mean :    91.39 ms
  Std  :     0.14 ms



Running small | forward_backward

Building model
  Parameters: 128.6M

  Warming up for 5 step(s)...

Results  [forward_backward | small | ctx=512]
  Mean :   149.14 ms
  Std  :     0.31 ms



Running medium | forward

Building model
  Parameters: 423.2M

  Warming up for 5 step(s)...

Results  [forward | medium | ctx=512]
  Mean :   133.94 ms
  Std  :     0.19 ms



Running medium | backward

Building model
  Parameters: 423.2M

  Warming up for 5 step(s)...

Results  [backward | medium | ctx=512]
  Mean :   274.29 ms
  Std  :     0.23 ms



Running medium | forward_backward

Building model
  Parameters: 423.2M

  Warming up for 5 step(s)...

Results  [forward_backward | medium | ctx=512]
  Mean :   447.32 ms
  Std  :     0.32 ms



Running large | forward

Building model
  Parameters: 969.4M

  Warming up for 5 step(s)...

Results  [forward | large | ctx=512]
  Mean :   279.25 ms
  Std  :     0.21 ms



Running large | backward

Building model
  Parameters: 969.4M

  Warming up for 5 step(s)...

Results  [backward | large | ctx=512]
  Mean :   590.61 ms
  Std  :     0.34 ms



Running large | forward_backward

Building model
  Parameters: 969.4M

  Warming up for 5 step(s)...

Results  [forward_backward | large | ctx=512]
  Mean :   960.86 ms
  Std  :     0.94 ms



Running xl | forward

Building model
  Parameters: 1998.2M

  Warming up for 5 step(s)...

Results  [forward | xl | ctx=512]
  Mean :   563.06 ms
  Std  :     0.78 ms



Running xl | backward

Building model
  Parameters: 1998.2M

  Warming up for 5 step(s)...

Results  [backward | xl | ctx=512]
  Mean :  1160.42 ms
  Std  :     0.75 ms



Running xl | forward_backward

Building model
  Parameters: 1998.2M

  Warming up for 5 step(s)...

Results  [forward_backward | xl | ctx=512]
  Mean :  1898.60 ms
  Std  :     0.86 ms



Running 2.7B | forward

Building model
  Parameters: 3406.8M

  Warming up for 5 step(s)...

Results  [forward | 2.7B | ctx=512]
  Mean :   842.41 ms
  Std  :     0.99 ms



Running 2.7B | backward

Building model
  Parameters: 3406.8M

  Warming up for 5 step(s)...

Results  [backward | 2.7B | ctx=512]
  Mean :  1736.12 ms
  Std  :     1.26 ms



Running 2.7B | forward_backward

Building model
  Parameters: 3406.8M

  Warming up for 5 step(s)...

Results  [forward_backward | 2.7B | ctx=512]
  Mean :  2865.14 ms
  Std  :     2.64 ms

      size              mode  mean_ms
0    small           forward    45.04
1    small          backward    91.39
2    small  forward_backward   149.14
3   medium           forward   133.94
4   medium          backward   274.29
5   medium  forward_backward   447.32
6    large           forward   279.25
7    large          backward   590.61
8    large  forward_backward   960.86
9       xl           forward   563.06
10      xl          backward  1160.42
11      xl  forward_backward  1898.60
12    2.7B           forward   842.41
13    2.7B          backward  1736.12
14    2.7B  forward_backward  2865.14

### c) Part

#### Only Mean

In [10]:
import subprocess
import pandas as pd
import re

sizes = ["small", "medium", "large", "xl", "2.7B"]
modes = ["forward", "backward", "forward_backward"]
warmups = [0, 1, 2, 5]

results = []

for warmup in warmups:
    print("\n==============================")
    print(f"WARMUP STEPS = {warmup}")
    print("==============================")

    for size in sizes:
        for mode in modes:

            cmd = f"""
            uv run python ./student/benchmarking_script.py \
                --size {size} \
                --context_length 512 \
                --mode {mode} \
                --warmup_steps {warmup} \
                --n_steps 10
            """

            output = subprocess.check_output(cmd, shell=True, text=True)

            print(output)

            match = re.search(r"Mean\s*:\s*([\d\.]+)\s*ms", output)

            if match:
                results.append({
                    "size": size,
                    "mode": mode,
                    "warmup": warmup,
                    "mean_ms": float(match.group(1))
                })

df = pd.DataFrame(results)
df

==============================
WARMUP STEPS = 0
==============================

Building model
  Parameters: 128.6M

Warm up steps being used

Results  [forward | small | ctx=512]
  Mean :   110.25 ms


Building model
  Parameters: 128.6M

Warm up steps being used

Results  [backward | small | ctx=512]
  Mean :   102.53 ms


Building model
  Parameters: 128.6M

Warm up steps being used

Results  [forward_backward | small | ctx=512]
  Mean :   225.16 ms


Building model
  Parameters: 423.2M

Warm up steps being used

Results  [forward | medium | ctx=512]
  Mean :   187.78 ms


Building model
  Parameters: 423.2M

Warm up steps being used

Results  [backward | medium | ctx=512]
  Mean :   285.85 ms


Building model
  Parameters: 423.2M

Warm up steps being used

Results  [forward_backward | medium | ctx=512]
  Mean :   512.04 ms


Building model
  Parameters: 969.4M

Warm up steps being used

Results  [forward | large | ctx=512]
  Mean :   332.28 ms


Building model
  Parameters: 969.4M

Warm up steps being used

Results  [backward | large | ctx=512]
  Mean :   599.47 ms


Building model
  Parameters: 969.4M

Warm up steps being used

Results  [forward_backward | large | ctx=512]
  Mean :  1020.44 ms


Building model
  Parameters: 1998.2M

Warm up steps being used

Results  [forward | xl | ctx=512]
  Mean :   615.82 ms


Building model
  Parameters: 1998.2M

Warm up steps being used

Results  [backward | xl | ctx=512]
  Mean :  1169.63 ms


Building model
  Parameters: 1998.2M

Warm up steps being used

Results  [forward_backward | xl | ctx=512]
  Mean :  1962.13 ms


Building model
  Parameters: 3406.8M

Warm up steps being used

Results  [forward | 2.7B | ctx=512]
  Mean :   896.16 ms


Building model
  Parameters: 3406.8M

Warm up steps being used

Results  [backward | 2.7B | ctx=512]
  Mean :  1743.65 ms


Building model
  Parameters: 3406.8M

Warm up steps being used

Results  [forward_backward | 2.7B | ctx=512]
  Mean :  2927.99 ms


==============================
WARMUP STEPS = 1
==============================

Building model
  Parameters: 128.6M

Warm up steps being used

Results  [forward | small | ctx=512]
  Mean :    46.46 ms


Building model
  Parameters: 128.6M

Warm up steps being used

Results  [backward | small | ctx=512]
  Mean :    90.96 ms


Building model
  Parameters: 128.6M

Warm up steps being used

Results  [forward_backward | small | ctx=512]
  Mean :   148.63 ms


Building model
  Parameters: 423.2M

Warm up steps being used

Results  [forward | medium | ctx=512]
  Mean :   134.13 ms


Building model
  Parameters: 423.2M

Warm up steps being used

Results  [backward | medium | ctx=512]
  Mean :   274.32 ms


Building model
  Parameters: 423.2M

Warm up steps being used

Results  [forward_backward | medium | ctx=512]
  Mean :   448.14 ms


Building model
  Parameters: 969.4M

Warm up steps being used

Results  [forward | large | ctx=512]
  Mean :   278.96 ms


Building model
  Parameters: 969.4M

Warm up steps being used

Results  [backward | large | ctx=512]
  Mean :   589.53 ms


Building model
  Parameters: 969.4M

Warm up steps being used

Results  [forward_backward | large | ctx=512]
  Mean :   956.68 ms


Building model
  Parameters: 1998.2M

Warm up steps being used

Results  [forward | xl | ctx=512]
  Mean :   562.16 ms


Building model
  Parameters: 1998.2M

Warm up steps being used

Results  [backward | xl | ctx=512]
  Mean :  1159.43 ms


Building model
  Parameters: 1998.2M

Warm up steps being used

Results  [forward_backward | xl | ctx=512]
  Mean :  1893.84 ms


Building model
  Parameters: 3406.8M

Warm up steps being used

Results  [forward | 2.7B | ctx=512]
  Mean :   841.25 ms


Building model
  Parameters: 3406.8M

Warm up steps being used

Results  [backward | 2.7B | ctx=512]
  Mean :  1733.71 ms


Building model
  Parameters: 3406.8M

Warm up steps being used

Results  [forward_backward | 2.7B | ctx=512]
  Mean :  2861.93 ms


==============================
WARMUP STEPS = 2
==============================

Building model
  Parameters: 128.6M

Warm up steps being used

Results  [forward | small | ctx=512]
  Mean :    46.56 ms


Building model
  Parameters: 128.6M

Warm up steps being used

Results  [backward | small | ctx=512]
  Mean :    90.96 ms


Building model
  Parameters: 128.6M

Warm up steps being used

Results  [forward_backward | small | ctx=512]
  Mean :   148.93 ms


Building model
  Parameters: 423.2M

Warm up steps being used

Results  [forward | medium | ctx=512]
  Mean :   134.13 ms


Building model
  Parameters: 423.2M

Warm up steps being used

Results  [backward | medium | ctx=512]
  Mean :   274.33 ms


Building model
  Parameters: 423.2M

Warm up steps being used

Results  [forward_backward | medium | ctx=512]
  Mean :   446.33 ms


Building model
  Parameters: 969.4M

Warm up steps being used

Results  [forward | large | ctx=512]
  Mean :   278.95 ms


Building model
  Parameters: 969.4M

Warm up steps being used

Results  [backward | large | ctx=512]
  Mean :   589.50 ms


Building model
  Parameters: 969.4M

Warm up steps being used

Results  [forward_backward | large | ctx=512]
  Mean :   956.83 ms


Building model
  Parameters: 1998.2M

Warm up steps being used

Results  [forward | xl | ctx=512]
  Mean :   561.90 ms


Building model
  Parameters: 1998.2M

Warm up steps being used

Results  [backward | xl | ctx=512]
  Mean :  1159.63 ms


Building model
  Parameters: 1998.2M

Warm up steps being used

Results  [forward_backward | xl | ctx=512]
  Mean :  1895.35 ms


Building model
  Parameters: 3406.8M

Warm up steps being used

Results  [forward | 2.7B | ctx=512]
  Mean :   841.05 ms


Building model
  Parameters: 3406.8M

Warm up steps being used

Results  [backward | 2.7B | ctx=512]
  Mean :  1733.44 ms


Building model
  Parameters: 3406.8M

Warm up steps being used

Results  [forward_backward | 2.7B | ctx=512]
  Mean :  2861.55 ms


==============================
WARMUP STEPS = 5
==============================

Building model
  Parameters: 128.6M

Warm up steps being used

Results  [forward | small | ctx=512]
  Mean :    45.12 ms


Building model
  Parameters: 128.6M

Warm up steps being used

Results  [backward | small | ctx=512]
  Mean :    90.86 ms


Building model
  Parameters: 128.6M

Warm up steps being used

Results  [forward_backward | small | ctx=512]
  Mean :   149.04 ms


Building model
  Parameters: 423.2M

Warm up steps being used

Results  [forward | medium | ctx=512]
  Mean :   133.98 ms


Building model
  Parameters: 423.2M

Warm up steps being used

Results  [backward | medium | ctx=512]
  Mean :   274.29 ms


Building model
  Parameters: 423.2M

Warm up steps being used

Results  [forward_backward | medium | ctx=512]
  Mean :   447.04 ms


Building model
  Parameters: 969.4M

Warm up steps being used

Results  [forward | large | ctx=512]
  Mean :   279.25 ms


Building model
  Parameters: 969.4M

Warm up steps being used

Results  [backward | large | ctx=512]
  Mean :   589.61 ms


Building model
  Parameters: 969.4M

Warm up steps being used

Results  [forward_backward | large | ctx=512]
  Mean :   957.72 ms


Building model
  Parameters: 1998.2M

Warm up steps being used

Results  [forward | xl | ctx=512]
  Mean :   561.85 ms


Building model
  Parameters: 1998.2M

Warm up steps being used

Results  [backward | xl | ctx=512]
  Mean :  1159.88 ms


Building model
  Parameters: 1998.2M

Warm up steps being used

Results  [forward_backward | xl | ctx=512]
  Mean :  1893.67 ms


Building model
  Parameters: 3406.8M

Warm up steps being used

Results  [forward | 2.7B | ctx=512]
  Mean :   841.00 ms


Building model
  Parameters: 3406.8M

Warm up steps being used

Results  [backward | 2.7B | ctx=512]
  Mean :  1733.62 ms


Building model
  Parameters: 3406.8M

Warm up steps being used

Results  [forward_backward | 2.7B | ctx=512]
  Mean :  2864.84 ms

      size              mode  warmup  mean_ms
0    small           forward       0   110.25
1    small          backward       0   102.53
2    small  forward_backward       0   225.16
3   medium           forward       0   187.78
4   medium          backward       0   285.85
5   medium  forward_backward       0   512.04
6    large           forward       0   332.28
7    large          backward       0   599.47
8    large  forward_backward       0  1020.44
9       xl           forward       0   615.82
10      xl          backward       0  1169.63
11      xl  forward_backward       0  1962.13
12    2.7B           forward       0   896.16
13    2.7B          backward       0  1743.65
14    2.7B  forward_backward       0  2927.99
15   small           forward       1    46.46
16   small          backward       1    90.96
17   small  forward_backward       1   148.63
18  medium           forward       1   134.13
19  medium          backward       1   274.32
20  medium  forward_backward       1   448.14
21   large           forward       1   278.96
22   large          backward       1   589.53
23   large  forward_backward       1   956.68
24      xl           forward       1   562.16
25      xl          backward       1  1159.43
26      xl  forward_backward       1  1893.84
27    2.7B           forward       1   841.25
28    2.7B          backward       1  1733.71
29    2.7B  forward_backward       1  2861.93
30   small           forward       2    46.56
31   small          backward       2    90.96
32   small  forward_backward       2   148.93
33  medium           forward       2   134.13
34  medium          backward       2   274.33
35  medium  forward_backward       2   446.33
36   large           forward       2   278.95
37   large          backward       2   589.50
38   large  forward_backward       2   956.83
39      xl           forward       2   561.90
40      xl          backward       2  1159.63
41      xl  forward_backward       2  1895.35
42    2.7B           forward       2   841.05
43    2.7B          backward       2  1733.44
44    2.7B  forward_backward       2  2861.55
45   small           forward       5    45.12
46   small          backward       5    90.86
47   small  forward_backward       5   149.04
48  medium           forward       5   133.98
49  medium          backward       5   274.29
50  medium  forward_backward       5   447.04
51   large           forward       5   279.25
52   large          backward       5   589.61
53   large  forward_backward       5   957.72
54      xl           forward       5   561.85
55      xl          backward       5  1159.88
56      xl  forward_backward       5  1893.67
57    2.7B           forward       5   841.00
58    2.7B          backward       5  1733.62
59    2.7B  forward_backward       5  2864.84

#### STD + Mean With warm up

In [7]:
import subprocess
import pandas as pd
import re

sizes = ["small", "medium", "large", "xl", "2.7B"]
modes = ["forward", "backward", "forward_backward"]
warmups = [0, 1, 2, 5]

results = []

for warmup in warmups:
    print("\n==============================")
    print(f"WARMUP STEPS = {warmup}")
    print("==============================")

    for size in sizes:
        for mode in modes:

            cmd = f"""
            uv run python ./student/benchmarking_script.py \
                --size {size} \
                --context_length 512 \
                --mode {mode} \
                --warmup_steps {warmup} \
                --n_steps 10
            """

            output = subprocess.check_output(cmd, shell=True, text=True)

            print(output)

            match = re.search(r"Mean\s*:\s*([\d\.]+)\s*ms", output)

            if match:
                results.append({
                    "size": size,
                    "mode": mode,
                    "warmup": warmup,
                    "mean_ms": float(match.group(1))
                })

df = pd.DataFrame(results)
df

==============================
WARMUP STEPS = 0
==============================

Building model
  Parameters: 128.6M

  Warming up for 0 step(s)...

Results  [forward | small | ctx=512]
  Mean :   109.98 ms
  Std  :   193.45 ms



Building model
  Parameters: 128.6M

  Warming up for 0 step(s)...

Results  [backward | small | ctx=512]
  Mean :   102.92 ms
  Std  :    36.77 ms



Building model
  Parameters: 128.6M

  Warming up for 0 step(s)...

Results  [forward_backward | small | ctx=512]
  Mean :   227.09 ms
  Std  :   245.60 ms



Building model
  Parameters: 423.2M

  Warming up for 0 step(s)...

Results  [forward | medium | ctx=512]
  Mean :   188.03 ms
  Std  :   166.61 ms



Building model
  Parameters: 423.2M

  Warming up for 0 step(s)...

Results  [backward | medium | ctx=512]
  Mean :   285.42 ms
  Std  :    33.20 ms



Building model
  Parameters: 423.2M

  Warming up for 0 step(s)...

Results  [forward_backward | medium | ctx=512]
  Mean :   512.44 ms
  Std  :   203.67 ms



Building model
  Parameters: 969.4M

  Warming up for 0 step(s)...

Results  [forward | large | ctx=512]
  Mean :   331.58 ms
  Std  :   163.84 ms



Building model
  Parameters: 969.4M

  Warming up for 0 step(s)...

Results  [backward | large | ctx=512]
  Mean :   601.75 ms
  Std  :    32.69 ms



Building model
  Parameters: 969.4M

  Warming up for 0 step(s)...

Results  [forward_backward | large | ctx=512]
  Mean :  1027.47 ms
  Std  :   212.56 ms



Building model
  Parameters: 1998.2M

  Warming up for 0 step(s)...

Results  [forward | xl | ctx=512]
  Mean :   619.26 ms
  Std  :   177.05 ms



Building model
  Parameters: 1998.2M

  Warming up for 0 step(s)...

Results  [backward | xl | ctx=512]
  Mean :  1172.61 ms
  Std  :    33.47 ms



Building model
  Parameters: 1998.2M

  Warming up for 0 step(s)...

Results  [forward_backward | xl | ctx=512]
  Mean :  1967.31 ms
  Std  :   209.32 ms



Building model
  Parameters: 3406.8M

  Warming up for 0 step(s)...

Results  [forward | 2.7B | ctx=512]
  Mean :   898.83 ms
  Std  :   172.44 ms



Building model
  Parameters: 3406.8M

  Warming up for 0 step(s)...

Results  [backward | 2.7B | ctx=512]
  Mean :  1749.10 ms
  Std  :    31.84 ms



Building model
  Parameters: 3406.8M

  Warming up for 0 step(s)...

Results  [forward_backward | 2.7B | ctx=512]
  Mean :  2934.18 ms
  Std  :   208.67 ms



==============================
WARMUP STEPS = 1
==============================

Building model
  Parameters: 128.6M

  Warming up for 1 step(s)...

Results  [forward | small | ctx=512]
  Mean :    45.87 ms
  Std  :     1.29 ms



Building model
  Parameters: 128.6M

  Warming up for 1 step(s)...

Results  [backward | small | ctx=512]
  Mean :    91.18 ms
  Std  :     0.20 ms



Building model
  Parameters: 128.6M

  Warming up for 1 step(s)...

Results  [forward_backward | small | ctx=512]
  Mean :   149.91 ms
  Std  :     0.54 ms



Building model
  Parameters: 423.2M

  Warming up for 1 step(s)...

Results  [forward | medium | ctx=512]
  Mean :   136.10 ms
  Std  :     4.86 ms



Building model
  Parameters: 423.2M

  Warming up for 1 step(s)...

Results  [backward | medium | ctx=512]
  Mean :   275.11 ms
  Std  :     0.25 ms



Building model
  Parameters: 423.2M

  Warming up for 1 step(s)...

Results  [forward_backward | medium | ctx=512]
  Mean :   447.13 ms
  Std  :     0.25 ms



Building model
  Parameters: 969.4M

  Warming up for 1 step(s)...

Results  [forward | large | ctx=512]
  Mean :   279.89 ms
  Std  :     0.34 ms



Building model
  Parameters: 969.4M

  Warming up for 1 step(s)...

Results  [backward | large | ctx=512]
  Mean :   590.89 ms
  Std  :     0.49 ms



Building model
  Parameters: 969.4M

  Warming up for 1 step(s)...

Results  [forward_backward | large | ctx=512]
  Mean :   960.82 ms
  Std  :     0.89 ms



Building model
  Parameters: 1998.2M

  Warming up for 1 step(s)...

Results  [forward | xl | ctx=512]
  Mean :   562.52 ms
  Std  :     0.67 ms



Building model
  Parameters: 1998.2M

  Warming up for 1 step(s)...

Results  [backward | xl | ctx=512]
  Mean :  1163.97 ms
  Std  :     0.73 ms



Building model
  Parameters: 1998.2M

  Warming up for 1 step(s)...

Results  [forward_backward | xl | ctx=512]
  Mean :  1900.83 ms
  Std  :     1.52 ms



Building model
  Parameters: 3406.8M

  Warming up for 1 step(s)...

Results  [forward | 2.7B | ctx=512]
  Mean :   843.32 ms
  Std  :     0.91 ms



Building model
  Parameters: 3406.8M

  Warming up for 1 step(s)...

Results  [backward | 2.7B | ctx=512]
  Mean :  1735.37 ms
  Std  :     1.82 ms



Building model
  Parameters: 3406.8M

  Warming up for 1 step(s)...

Results  [forward_backward | 2.7B | ctx=512]
  Mean :  2864.18 ms
  Std  :     1.98 ms



==============================
WARMUP STEPS = 2
==============================

Building model
  Parameters: 128.6M

  Warming up for 2 step(s)...

Results  [forward | small | ctx=512]
  Mean :    45.15 ms
  Std  :     0.29 ms



Building model
  Parameters: 128.6M

  Warming up for 2 step(s)...

Results  [backward | small | ctx=512]
  Mean :    91.22 ms
  Std  :     0.12 ms



Building model
  Parameters: 128.6M

  Warming up for 2 step(s)...

Results  [forward_backward | small | ctx=512]
  Mean :   149.36 ms
  Std  :     0.37 ms



Building model
  Parameters: 423.2M

  Warming up for 2 step(s)...

Results  [forward | medium | ctx=512]
  Mean :   134.53 ms
  Std  :     0.31 ms



Building model
  Parameters: 423.2M

  Warming up for 2 step(s)...

Results  [backward | medium | ctx=512]
  Mean :   275.28 ms
  Std  :     0.28 ms



Building model
  Parameters: 423.2M

  Warming up for 2 step(s)...

Results  [forward_backward | medium | ctx=512]
  Mean :   447.47 ms
  Std  :     0.37 ms



Building model
  Parameters: 969.4M

  Warming up for 2 step(s)...

Results  [forward | large | ctx=512]
  Mean :   279.83 ms
  Std  :     0.20 ms



Building model
  Parameters: 969.4M

  Warming up for 2 step(s)...

Results  [backward | large | ctx=512]
  Mean :   592.31 ms
  Std  :     0.19 ms



Building model
  Parameters: 969.4M

  Warming up for 2 step(s)...

Results  [forward_backward | large | ctx=512]
  Mean :   960.39 ms
  Std  :     0.74 ms



Building model
  Parameters: 1998.2M

  Warming up for 2 step(s)...

Results  [forward | xl | ctx=512]
  Mean :   563.77 ms
  Std  :     0.77 ms



Building model
  Parameters: 1998.2M

  Warming up for 2 step(s)...

Results  [backward | xl | ctx=512]
  Mean :  1163.21 ms
  Std  :     0.78 ms



Building model
  Parameters: 1998.2M

  Warming up for 2 step(s)...

Results  [forward_backward | xl | ctx=512]
  Mean :  1900.92 ms
  Std  :     1.04 ms



Building model
  Parameters: 3406.8M

  Warming up for 2 step(s)...

Results  [forward | 2.7B | ctx=512]
  Mean :   844.77 ms
  Std  :     1.13 ms



Building model
  Parameters: 3406.8M

  Warming up for 2 step(s)...

Results  [backward | 2.7B | ctx=512]
  Mean :  1737.86 ms
  Std  :     1.26 ms



Building model
  Parameters: 3406.8M

  Warming up for 2 step(s)...

Results  [forward_backward | 2.7B | ctx=512]
  Mean :  2869.08 ms
  Std  :     2.19 ms



==============================
WARMUP STEPS = 5
==============================

Building model
  Parameters: 128.6M

  Warming up for 5 step(s)...

Results  [forward | small | ctx=512]
  Mean :    44.99 ms
  Std  :     0.07 ms



Building model
  Parameters: 128.6M

  Warming up for 5 step(s)...

Results  [backward | small | ctx=512]
  Mean :    91.13 ms
  Std  :     0.12 ms



Building model
  Parameters: 128.6M

  Warming up for 5 step(s)...

Results  [forward_backward | small | ctx=512]
  Mean :   149.22 ms
  Std  :     0.38 ms



Building model
  Parameters: 423.2M

  Warming up for 5 step(s)...

Results  [forward | medium | ctx=512]
  Mean :   134.19 ms
  Std  :     0.24 ms



Building model
  Parameters: 423.2M

  Warming up for 5 step(s)...

Results  [backward | medium | ctx=512]
  Mean :   274.89 ms
  Std  :     0.31 ms



Building model
  Parameters: 423.2M

  Warming up for 5 step(s)...

Results  [forward_backward | medium | ctx=512]
  Mean :   448.17 ms
  Std  :     0.25 ms



Building model
  Parameters: 969.4M

  Warming up for 5 step(s)...

Results  [forward | large | ctx=512]
  Mean :   279.73 ms
  Std  :     0.27 ms



Building model
  Parameters: 969.4M

  Warming up for 5 step(s)...

Results  [backward | large | ctx=512]
  Mean :   591.61 ms
  Std  :     0.45 ms



Building model
  Parameters: 969.4M

  Warming up for 5 step(s)...

Results  [forward_backward | large | ctx=512]
  Mean :   961.44 ms
  Std  :     0.65 ms



Building model
  Parameters: 1998.2M

  Warming up for 5 step(s)...

Results  [forward | xl | ctx=512]
  Mean :   563.32 ms
  Std  :     0.50 ms



Building model
  Parameters: 1998.2M

  Warming up for 5 step(s)...

Results  [backward | xl | ctx=512]
  Mean :  1163.32 ms
  Std  :     0.96 ms



Building model
  Parameters: 1998.2M

  Warming up for 5 step(s)...

Results  [forward_backward | xl | ctx=512]
  Mean :  1897.67 ms
  Std  :     0.85 ms



Building model
  Parameters: 3406.8M

  Warming up for 5 step(s)...

Results  [forward | 2.7B | ctx=512]
  Mean :   842.17 ms
  Std  :     0.90 ms



Building model
  Parameters: 3406.8M

  Warming up for 5 step(s)...

Results  [backward | 2.7B | ctx=512]
  Mean :  1736.50 ms
  Std  :     0.56 ms



Building model
  Parameters: 3406.8M

  Warming up for 5 step(s)...

Results  [forward_backward | 2.7B | ctx=512]
  Mean :  2866.04 ms
  Std  :     1.86 ms

      size              mode  warmup  mean_ms
0    small           forward       0   109.98
1    small          backward       0   102.92
2    small  forward_backward       0   227.09
3   medium           forward       0   188.03
4   medium          backward       0   285.42
5   medium  forward_backward       0   512.44
6    large           forward       0   331.58
7    large          backward       0   601.75
8    large  forward_backward       0  1027.47
9       xl           forward       0   619.26
10      xl          backward       0  1172.61
11      xl  forward_backward       0  1967.31
12    2.7B           forward       0   898.83
13    2.7B          backward       0  1749.10
14    2.7B  forward_backward       0  2934.18
15   small           forward       1    45.87
16   small          backward       1    91.18
17   small  forward_backward       1   149.91
18  medium           forward       1   136.10
19  medium          backward       1   275.11
20  medium  forward_backward       1   447.13
21   large           forward       1   279.89
22   large          backward       1   590.89
23   large  forward_backward       1   960.82
24      xl           forward       1   562.52
25      xl          backward       1  1163.97
26      xl  forward_backward       1  1900.83
27    2.7B           forward       1   843.32
28    2.7B          backward       1  1735.37
29    2.7B  forward_backward       1  2864.18
30   small           forward       2    45.15
31   small          backward       2    91.22
32   small  forward_backward       2   149.36
33  medium           forward       2   134.53
34  medium          backward       2   275.28
35  medium  forward_backward       2   447.47
36   large           forward       2   279.83
37   large          backward       2   592.31
38   large  forward_backward       2   960.39
39      xl           forward       2   563.77
40      xl          backward       2  1163.21
41      xl  forward_backward       2  1900.92
42    2.7B           forward       2   844.77
43    2.7B          backward       2  1737.86
44    2.7B  forward_backward       2  2869.08
45   small           forward       5    44.99
46   small          backward       5    91.13
47   small  forward_backward       5   149.22
48  medium           forward       5   134.19
49  medium          backward       5   274.89
50  medium  forward_backward       5   448.17
51   large           forward       5   279.73
52   large          backward       5   591.61
53   large  forward_backward       5   961.44
54      xl           forward       5   563.32
55      xl          backward       5  1163.32
56      xl  forward_backward       5  1897.67
57    2.7B           forward       5   842.17
58    2.7B          backward       5  1736.50
59    2.7B  forward_backward       5  2866.04

## Part 2 : Nsys Profiling

In [7]:
!which nsys || echo "nsys not found in this runtime"

nsys not found in this runtime

In [11]:
!apt-get update
!apt-get install -y --no-install-recommends gnupg

!echo "deb http://developer.download.nvidia.com/devtools/repos/ubuntu$(source /etc/lsb-release; echo "$DISTRIB_RELEASE" | tr -d .)/$(dpkg --print-architecture) /" \
  | tee /etc/apt/sources.list.d/nvidia-devtools.list

!apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub

!apt-get update
!apt-get install -y nsight-systems-cli
!nsys --version

Hit:1 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:3 https://cli.github.com/packages stable InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:5 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:6 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:9 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:10 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Hit:11 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
gnupg is already the newest version (2.2.27-3ubuntu2.5).
gnupg set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 98 not upgraded.
deb http://developer.download.nvidia.com/devtools/repos/ubuntu2204/amd64 /
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
Executing: /tmp/apt-key-gpghome.Wvvk8nRqL3/gpg.1.sh --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
gpg: requesting key from 'http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub'
gpg: key F60F4B3D7FA2AF80: public key "cudatools <cudatools@nvidia.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
Hit:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:3 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:4 https://cli.github.com/packages stable InRelease
Hit:5 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:6 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:7 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:8 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:9 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:10 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:11 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Hit:12 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Ign:1 https://developer.download.nvidia.com/devtools/repos/ubuntu2204/amd64  InRelease
Get:13 https://developer.download.nvidia.com/devtools/repos/ubuntu2204/amd64  Release [496 B]
Get:14 https://developer.download.nvidia.com/devtools/repos/ubuntu2204/amd64  Release.gpg [833 B]
Get:15 https://developer.download.nvidia.com/devtools/repos/ubuntu2204/amd64  Packages [19.6 kB]
Fetched 20.9 kB in 8s (2,501 B/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
W: http://developer.download.nvidia.com/devtools/repos/ubuntu2204/amd64/Release.gpg: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  nsight-systems-cli-2026.1.1
The following NEW packages will be installed:
  nsight-systems-cli nsight-systems-cli-2026.1.1
0 upgraded, 2 newly installed, 0 to remove and 98 not upgraded.
Need to get 208 MB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 https://developer.download.nvidia.com/devtools/repos/ubuntu2204/amd64  nsight-systems-cli-2026.1.1 2026.1.1.204-261137176666v0 [208 MB]
Get:2 https://developer.download.nvidia.com/devtools/repos/ubuntu2204/amd64  nsight-systems-cli 2026.1.1.204 [2,028 B]
Fetched 208 MB in 1min 28s (2,368 kB/s)
Selecting previously unselected package nsight-systems-cli-2026.1.1.
(Reading database ... 121852 files and directories currently installed.)
Preparing to unpack .../nsight-systems-cli-2026.1.1_2026.1.1.204-261137176666v0_amd64.deb ...
Unpacking nsight-systems-cli-2026.1.1 (2026.1.1.204-261137176666v0) ...
Selecting previously unselected package nsight-systems-cli.
Preparing to unpack .../nsight-systems-cli_2026.1.1.204_amd64.deb ...
Unpacking nsight-systems-cli (2026.1.1.204) ...
Setting up nsight-systems-cli-2026.1.1 (2026.1.1.204-261137176666v0) ...
update-alternatives: using /opt/nvidia/nsight-systems-cli/2026.1.1/target-linux-x64/nsys to provide /usr/local/bin/nsys (nsys) in auto mode
Setting up nsight-systems-cli (2026.1.1.204) ...
NVIDIA Nsight Systems version 2026.1.1.204-261137176666v0

In [12]:
!nsys --version

NVIDIA Nsight Systems version 2026.1.1.204-261137176666v0

### 2. profiling script a)

In [13]:
import os
import subprocess
import pandas as pd

sizes = ["small", "medium", "large", "xl", "2.7B"]
contexts = [128, 256, 512, 1024]
modes = ["forward", "backward", "forward_backward"]

os.makedirs("nsys_profiles", exist_ok=True)
os.makedirs("nsys_stats", exist_ok=True)

for size in sizes:
    for ctx in contexts:
        for mode in modes:
            tag = f"{size}_ctx{ctx}_{mode}"
            out_base = f"nsys_profiles/{tag}"

            cmd = f"""
            nsys profile \
              --force-overwrite true \
              -t cuda,nvtx,osrt \
              -o {out_base} \
              uv run python ./student/nsys_profile.py \
                --size "{size}" \
                --context_length {ctx} \
                --mode {mode} \
                --warmup_steps 5 \
                --n_steps 10
            """

            print(f"\nRunning {tag}")
            try:
                subprocess.run(cmd, shell=True, check=True)

                stats_cmd = f"""
                nsys stats \
                  --report nvtx_sum \
                  --format csv \
                  {out_base}.nsys-rep > nsys_stats/{tag}_nvtx.csv
                """
                subprocess.run(stats_cmd, shell=True, check=True)

            except subprocess.CalledProcessError:
                print(f"OOM or failed for {tag}")

Running small_ctx128_forward

Running small_ctx128_backward

Running small_ctx128_forward_backward

Running small_ctx256_forward

Running small_ctx256_backward

Running small_ctx256_forward_backward

Running small_ctx512_forward

Running small_ctx512_backward

Running small_ctx512_forward_backward

Running small_ctx1024_forward

Running small_ctx1024_backward

Running small_ctx1024_forward_backward

Running medium_ctx128_forward

Running medium_ctx128_backward

Running medium_ctx128_forward_backward

Running medium_ctx256_forward

Running medium_ctx256_backward

Running medium_ctx256_forward_backward

Running medium_ctx512_forward

Running medium_ctx512_backward

Running medium_ctx512_forward_backward

Running medium_ctx1024_forward

Running medium_ctx1024_backward

Running medium_ctx1024_forward_backward

Running large_ctx128_forward

Running large_ctx128_backward

Running large_ctx128_forward_backward

Running large_ctx256_forward

Running large_ctx256_backward

Running large_ctx256_forward_backward

Running large_ctx512_forward

Running large_ctx512_backward

Running large_ctx512_forward_backward

Running large_ctx1024_forward

Running large_ctx1024_backward

Running large_ctx1024_forward_backward

Running xl_ctx128_forward

Running xl_ctx128_backward

Running xl_ctx128_forward_backward

Running xl_ctx256_forward

Running xl_ctx256_backward

Running xl_ctx256_forward_backward

Running xl_ctx512_forward

Running xl_ctx512_backward

Running xl_ctx512_forward_backward

Running xl_ctx1024_forward

Running xl_ctx1024_backward
OOM or failed for xl_ctx1024_backward

Running xl_ctx1024_forward_backward
OOM or failed for xl_ctx1024_forward_backward

Running 2.7B_ctx128_forward

Running 2.7B_ctx128_backward

Running 2.7B_ctx128_forward_backward

Running 2.7B_ctx256_forward

Running 2.7B_ctx256_backward

Running 2.7B_ctx256_forward_backward

Running 2.7B_ctx512_forward

Running 2.7B_ctx512_backward

Running 2.7B_ctx512_forward_backward

Running 2.7B_ctx1024_forward

Running 2.7B_ctx1024_backward
OOM or failed for 2.7B_ctx1024_backward

Running 2.7B_ctx1024_forward_backward
OOM or failed for 2.7B_ctx1024_forward_backward

In [16]:
!zip -r nsys_profiles.zip nsys_profiles/

  adding: nsys_profiles/ (stored 0%)
  adding: nsys_profiles/small_ctx256_backward.nsys-rep (deflated 41%)
  adding: nsys_profiles/large_ctx128_forward_backward.nsys-rep (deflated 44%)
  adding: nsys_profiles/xl_ctx512_backward.nsys-rep (deflated 40%)
  adding: nsys_profiles/xl_ctx512_forward.nsys-rep (deflated 40%)
  adding: nsys_profiles/large_ctx128_forward.sqlite (deflated 69%)
  adding: nsys_profiles/large_ctx1024_backward.nsys-rep (deflated 39%)
  adding: nsys_profiles/large_ctx256_forward_backward.sqlite (deflated 71%)
  adding: nsys_profiles/medium_ctx512_forward.nsys-rep (deflated 43%)
  adding: nsys_profiles/large_ctx128_forward_backward.sqlite (deflated 71%)
  adding: nsys_profiles/large_ctx512_backward.nsys-rep (deflated 39%)
  adding: nsys_profiles/xl_ctx256_forward_backward.nsys-rep (deflated 42%)
  adding: nsys_profiles/medium_ctx256_forward_backward.nsys-rep (deflated 44%)
  adding: nsys_profiles/2.7B_ctx256_backward.nsys-rep (deflated 40%)
  adding: nsys_profiles/medium_ctx128_forward.nsys-rep (deflated 43%)
  adding: nsys_profiles/xl_ctx512_forward.sqlite (deflated 68%)
  adding: nsys_profiles/medium_ctx1024_forward.sqlite (deflated 69%)
  adding: nsys_profiles/medium_ctx512_forward_backward.sqlite (deflated 71%)
  adding: nsys_profiles/large_ctx512_forward_backward.sqlite (deflated 70%)
  adding: nsys_profiles/medium_ctx128_forward.sqlite (deflated 69%)
  adding: nsys_profiles/2.7B_ctx512_forward.nsys-rep (deflated 41%)
  adding: nsys_profiles/small_ctx256_forward.sqlite (deflated 69%)
  adding: nsys_profiles/xl_ctx1024_forward_backward.nsys-rep (deflated 42%)
  adding: nsys_profiles/xl_ctx128_forward.nsys-rep (deflated 42%)
  adding: nsys_profiles/2.7B_ctx128_forward_backward.sqlite (deflated 69%)
  adding: nsys_profiles/small_ctx1024_forward_backward.sqlite (deflated 70%)
  adding: nsys_profiles/medium_ctx1024_backward.nsys-rep (deflated 39%)
  adding: nsys_profiles/large_ctx256_forward_backward.nsys-rep (deflated 44%)
  adding: nsys_profiles/small_ctx512_forward.nsys-rep (deflated 44%)
  adding: nsys_profiles/medium_ctx1024_backward.sqlite (deflated 69%)
  adding: nsys_profiles/xl_ctx256_forward.sqlite (deflated 69%)
  adding: nsys_profiles/xl_ctx1024_backward.nsys-rep (deflated 41%)
  adding: nsys_profiles/xl_ctx1024_forward.nsys-rep (deflated 40%)
  adding: nsys_profiles/small_ctx256_forward_backward.nsys-rep (deflated 43%)
  adding: nsys_profiles/large_ctx128_forward.nsys-rep (deflated 42%)
  adding: nsys_profiles/small_ctx128_forward_backward.sqlite (deflated 71%)
  adding: nsys_profiles/2.7B_ctx512_forward_backward.sqlite (deflated 69%)
  adding: nsys_profiles/xl_ctx128_forward.sqlite (deflated 69%)
  adding: nsys_profiles/xl_ctx256_forward.nsys-rep (deflated 42%)
  adding: nsys_profiles/xl_ctx128_forward_backward.sqlite (deflated 71%)
  adding: nsys_profiles/xl_ctx256_backward.nsys-rep (deflated 40%)
  adding: nsys_profiles/medium_ctx256_forward.sqlite (deflated 69%)
  adding: nsys_profiles/small_ctx1024_forward_backward.nsys-rep (deflated 42%)
  adding: nsys_profiles/small_ctx256_forward_backward.sqlite (deflated 71%)
  adding: nsys_profiles/large_ctx512_forward.sqlite (deflated 69%)
  adding: nsys_profiles/large_ctx512_forward_backward.nsys-rep (deflated 43%)
  adding: nsys_profiles/large_ctx128_backward.nsys-rep (deflated 41%)
  adding: nsys_profiles/small_ctx512_backward.nsys-rep (deflated 42%)
  adding: nsys_profiles/medium_ctx128_forward_backward.nsys-rep (deflated 44%)
  adding: nsys_profiles/2.7B_ctx256_backward.sqlite (deflated 68%)
  adding: nsys_profiles/2.7B_ctx1024_forward_backward.nsys-rep (deflated 41%)
  adding: nsys_profiles/small_ctx512_forward_backward.sqlite (deflated 71%)
  adding: nsys_profiles/small_ctx1024_backward.nsys-rep (deflated 41%)
  adding: nsys_profiles/small_ctx256_forward.nsys-rep (deflated 43%)
  adding: nsys_profiles/2.7B_ctx512_backward.sqlite (deflated 68%)
  adding: nsys_profiles/large_ctx256_backward.nsys-rep (deflated 41%)
  adding: nsys_profiles/large_ctx256_forward.sqlite (deflated 69%)
  adding: nsys_profiles/medium_ctx512_forward_backward.nsys-rep (deflated 43%)
  adding: nsys_profiles/2.7B_ctx1024_backward.nsys-rep (deflated 41%)
  adding: nsys_profiles/large_ctx1024_forward_backward.nsys-rep (deflated 42%)
  adding: nsys_profiles/medium_ctx128_backward.nsys-rep (deflated 41%)
  adding: nsys_profiles/medium_ctx128_backward.sqlite (deflated 70%)
  adding: nsys_profiles/medium_ctx128_forward_backward.sqlite (deflated 71%)
  adding: nsys_profiles/small_ctx128_forward.sqlite (deflated 69%)
  adding: nsys_profiles/medium_ctx256_backward.nsys-rep (deflated 41%)
  adding: nsys_profiles/small_ctx128_forward.nsys-rep (deflated 39%)
  adding: nsys_profiles/2.7B_ctx128_forward_backward.nsys-rep (deflated 42%)
  adding: nsys_profiles/2.7B_ctx128_forward.sqlite (deflated 68%)
  adding: nsys_profiles/xl_ctx128_forward_backward.nsys-rep (deflated 43%)
  adding: nsys_profiles/large_ctx1024_forward.sqlite (deflated 68%)
  adding: nsys_profiles/2.7B_ctx256_forward_backward.sqlite (deflated 69%)
  adding: nsys_profiles/small_ctx512_forward.sqlite (deflated 69%)
  adding: nsys_profiles/small_ctx256_backward.sqlite (deflated 69%)
  adding: nsys_profiles/medium_ctx512_backward.sqlite (deflated 69%)
  adding: nsys_profiles/small_ctx128_forward_backward.nsys-rep (deflated 43%)
  adding: nsys_profiles/xl_ctx512_forward_backward.nsys-rep (deflated 42%)
  adding: nsys_profiles/large_ctx512_forward.nsys-rep (deflated 42%)
  adding: nsys_profiles/medium_ctx1024_forward.nsys-rep (deflated 44%)
  adding: nsys_profiles/xl_ctx256_backward.sqlite (deflated 69%)
  adding: nsys_profiles/2.7B_ctx128_backward.nsys-rep (deflated 41%)
  adding: nsys_profiles/medium_ctx512_forward.sqlite (deflated 69%)
  adding: nsys_profiles/medium_ctx256_forward.nsys-rep (deflated 43%)
  adding: nsys_profiles/xl_ctx512_backward.sqlite (deflated 69%)
  adding: nsys_profiles/xl_ctx128_backward.sqlite (deflated 70%)
  adding: nsys_profiles/xl_ctx128_backward.nsys-rep (deflated 41%)
  adding: nsys_profiles/small_ctx128_backward.sqlite (deflated 70%)
  adding: nsys_profiles/2.7B_ctx512_backward.nsys-rep (deflated 40%)
  adding: nsys_profiles/medium_ctx1024_forward_backward.nsys-rep (deflated 42%)
  adding: nsys_profiles/small_ctx128_backward.nsys-rep (deflated 42%)
  adding: nsys_profiles/large_ctx1024_forward.nsys-rep (deflated 41%)
  adding: nsys_profiles/medium_ctx256_backward.sqlite (deflated 70%)
  adding: nsys_profiles/2.7B_ctx512_forward_backward.nsys-rep (deflated 41%)
  adding: nsys_profiles/2.7B_ctx256_forward_backward.nsys-rep (deflated 42%)
  adding: nsys_profiles/xl_ctx512_forward_backward.sqlite (deflated 70%)
  adding: nsys_profiles/large_ctx256_forward.nsys-rep (deflated 44%)
  adding: nsys_profiles/large_ctx1024_backward.sqlite (deflated 68%)
  adding: nsys_profiles/xl_ctx256_forward_backward.sqlite (deflated 71%)
  adding: nsys_profiles/large_ctx512_backward.sqlite (deflated 69%)
  adding: nsys_profiles/xl_ctx1024_forward.sqlite (deflated 68%)
  adding: nsys_profiles/.zip (stored 0%)
  adding: nsys_profiles/2.7B_ctx1024_forward.nsys-rep (deflated 40%)
  adding: nsys_profiles/small_ctx512_backward.sqlite (deflated 69%)
  adding: nsys_profiles/medium_ctx256_forward_backward.sqlite (deflated 71%)
  adding: nsys_profiles/small_ctx1024_backward.sqlite (deflated 69%)
  adding: nsys_profiles/small_ctx512_forward_backward.nsys-rep (deflated 43%)
  adding: nsys_profiles/large_ctx128_backward.sqlite (deflated 70%)
  adding: nsys_profiles/2.7B_ctx1024_forward.sqlite (deflated 67%)
  adding: nsys_profiles/2.7B_ctx256_forward.sqlite (deflated 68%)
  adding: nsys_profiles/large_ctx256_backward.sqlite (deflated 70%)
  adding: nsys_profiles/medium_ctx512_backward.nsys-rep (deflated 40%)
  adding: nsys_profiles/2.7B_ctx128_forward.nsys-rep (deflated 42%)
  adding: nsys_profiles/2.7B_ctx128_backward.sqlite (deflated 69%)
  adding: nsys_profiles/small_ctx1024_forward.sqlite (deflated 69%)
  adding: nsys_profiles/medium_ctx1024_forward_backward.sqlite (deflated 70%)
  adding: nsys_profiles/2.7B_ctx256_forward.nsys-rep (deflated 42%)
  adding: nsys_profiles/large_ctx1024_forward_backward.sqlite (deflated 70%)
  adding: nsys_profiles/2.7B_ctx512_forward.sqlite (deflated 67%)
  adding: nsys_profiles/small_ctx1024_forward.nsys-rep (deflated 43%)

In [17]:
!zip -r nsys_stats.zip nsys_stats/

  adding: nsys_stats/ (stored 0%)
  adding: nsys_stats/large_ctx128_backward_nvtx.csv (deflated 58%)
  adding: nsys_stats/small_ctx128_forward_nvtx.csv (deflated 59%)
  adding: nsys_stats/medium_ctx128_forward_nvtx.csv (deflated 59%)
  adding: nsys_stats/large_ctx1024_forward_nvtx.csv (deflated 60%)
  adding: nsys_stats/medium_ctx512_backward_nvtx.csv (deflated 59%)
  adding: nsys_stats/small_ctx128_backward_nvtx.csv (deflated 59%)
  adding: nsys_stats/xl_ctx512_backward_nvtx.csv (deflated 59%)
  adding: nsys_stats/small_ctx256_backward_nvtx.csv (deflated 59%)
  adding: nsys_stats/2.7B_ctx128_forward_backward_nvtx.csv (deflated 58%)
  adding: nsys_stats/small_ctx1024_forward_nvtx.csv (deflated 60%)
  adding: nsys_stats/large_ctx1024_forward_backward_nvtx.csv (deflated 60%)
  adding: nsys_stats/large_ctx512_forward_backward_nvtx.csv (deflated 58%)
  adding: nsys_stats/2.7B_ctx256_forward_backward_nvtx.csv (deflated 59%)
  adding: nsys_stats/medium_ctx1024_forward_backward_nvtx.csv (deflated 59%)
  adding: nsys_stats/medium_ctx128_backward_nvtx.csv (deflated 58%)
  adding: nsys_stats/medium_ctx256_forward_nvtx.csv (deflated 60%)
  adding: nsys_stats/large_ctx128_forward_nvtx.csv (deflated 60%)
  adding: nsys_stats/medium_ctx1024_backward_nvtx.csv (deflated 58%)
  adding: nsys_stats/small_ctx256_forward_backward_nvtx.csv (deflated 58%)
  adding: nsys_stats/large_ctx256_forward_nvtx.csv (deflated 61%)
  adding: nsys_stats/large_ctx1024_backward_nvtx.csv (deflated 59%)
  adding: nsys_stats/small_ctx1024_backward_nvtx.csv (deflated 58%)
  adding: nsys_stats/small_ctx512_backward_nvtx.csv (deflated 59%)
  adding: nsys_stats/2.7B_ctx512_backward_nvtx.csv (deflated 59%)
  adding: nsys_stats/medium_ctx512_forward_nvtx.csv (deflated 60%)
  adding: nsys_stats/2.7B_ctx256_backward_nvtx.csv (deflated 59%)
  adding: nsys_stats/xl_ctx128_backward_nvtx.csv (deflated 58%)
  adding: nsys_stats/medium_ctx256_forward_backward_nvtx.csv (deflated 58%)
  adding: nsys_stats/medium_ctx1024_forward_nvtx.csv (deflated 60%)
  adding: nsys_stats/2.7B_ctx512_forward_backward_nvtx.csv (deflated 59%)
  adding: nsys_stats/medium_ctx256_backward_nvtx.csv (deflated 58%)
  adding: nsys_stats/xl_ctx512_forward_nvtx.csv (deflated 60%)
  adding: nsys_stats/xl_ctx256_forward_nvtx.csv (deflated 61%)
  adding: nsys_stats/xl_ctx128_forward_nvtx.csv (deflated 60%)
  adding: nsys_stats/small_ctx256_forward_nvtx.csv (deflated 59%)
  adding: nsys_stats/2.7B_ctx128_backward_nvtx.csv (deflated 59%)
  adding: nsys_stats/large_ctx256_forward_backward_nvtx.csv (deflated 58%)
  adding: nsys_stats/small_ctx512_forward_backward_nvtx.csv (deflated 58%)
  adding: nsys_stats/small_ctx1024_forward_backward_nvtx.csv (deflated 58%)
  adding: nsys_stats/medium_ctx128_forward_backward_nvtx.csv (deflated 58%)
  adding: nsys_stats/large_ctx512_backward_nvtx.csv (deflated 59%)
  adding: nsys_stats/small_ctx128_forward_backward_nvtx.csv (deflated 58%)
  adding: nsys_stats/2.7B_ctx128_forward_nvtx.csv (deflated 60%)
  adding: nsys_stats/xl_ctx512_forward_backward_nvtx.csv (deflated 59%)
  adding: nsys_stats/2.7B_ctx512_forward_nvtx.csv (deflated 61%)
  adding: nsys_stats/large_ctx256_backward_nvtx.csv (deflated 58%)
  adding: nsys_stats/large_ctx128_forward_backward_nvtx.csv (deflated 58%)
  adding: nsys_stats/xl_ctx128_forward_backward_nvtx.csv (deflated 58%)
  adding: nsys_stats/2.7B_ctx1024_forward_nvtx.csv (deflated 62%)
  adding: nsys_stats/medium_ctx512_forward_backward_nvtx.csv (deflated 59%)
  adding: nsys_stats/xl_ctx1024_forward_nvtx.csv (deflated 61%)
  adding: nsys_stats/xl_ctx256_backward_nvtx.csv (deflated 58%)
  adding: nsys_stats/small_ctx512_forward_nvtx.csv (deflated 59%)
  adding: nsys_stats/large_ctx512_forward_nvtx.csv (deflated 61%)
  adding: nsys_stats/2.7B_ctx256_forward_nvtx.csv (deflated 60%)
  adding: nsys_stats/xl_ctx256_forward_backward_nvtx.csv (deflated 59%)

## Part 3: Mixed Precision Profiling

### Part c)

In [7]:
import subprocess
import pandas as pd
import re

sizes = ["small", "medium", "large", "xl", "2.7B"]
modes = ["forward", "backward", "forward_backward"]

results = []

for size in sizes:
    for mode in modes:
        for mixed in [False, True]:
            precision = "bf16_mixed" if mixed else "fp32"

            cmd = f"""
            uv run python ./student/mixed_precision_profiling.py \
                --size "{size}" \
                --context_length 512 \
                --mode {mode} \
                --warmup_steps 5 \
                --n_steps 10 \
                {"--mixed_precision" if mixed else ""}
            """

            print(f"\nRunning size={size} | mode={mode} | precision={precision}")

            try:
                output = subprocess.check_output(cmd, shell=True, text=True, stderr=subprocess.STDOUT)
                print(output)

                mean_match = re.search(r"Mean\s*:\s*([\d\.]+)\s*ms", output)
                std_match = re.search(r"Std\s*:\s*([\d\.]+)\s*ms", output)
                param_match = re.search(r"Parameters:\s*([\d\.]+)M", output)

                results.append({
                    "size": size,
                    "mode": mode,
                    "precision": precision,
                    "params_m": float(param_match.group(1)) if param_match else None,
                    "mean_ms": float(mean_match.group(1)) if mean_match else None,
                    "std_ms": float(std_match.group(1)) if std_match else None,
                    "status": "ok",
                })

            except subprocess.CalledProcessError as e:
                print(e.output)
                results.append({
                    "size": size,
                    "mode": mode,
                    "precision": precision,
                    "params_m": None,
                    "mean_ms": None,
                    "std_ms": None,
                    "status": "failed/OOM",
                })

df = pd.DataFrame(results)
df

Running size=small | mode=forward | precision=fp32
Using CPython 3.12.12 interpreter at: /usr/bin/python3
Creating virtual environment at: .venv
Installed 75 packages in 253ms

  size=small  ctx=512  mode=forward  precision=FP32
  Parameters: 128.6M
  Mean :    58.49 ms
  Std  :    42.75 ms



Running size=small | mode=forward | precision=bf16_mixed

  size=small  ctx=512  mode=forward  precision=BF16 mixed
  Parameters: 128.6M
  Mean :    36.76 ms
  Std  :     0.38 ms



Running size=small | mode=backward | precision=fp32

  size=small  ctx=512  mode=backward  precision=FP32
  Parameters: 128.6M
  Mean :   137.94 ms
  Std  :     0.19 ms



Running size=small | mode=backward | precision=bf16_mixed

  size=small  ctx=512  mode=backward  precision=BF16 mixed
  Parameters: 128.6M
  Mean :    93.01 ms
  Std  :     2.86 ms



Running size=small | mode=forward_backward | precision=fp32

  size=small  ctx=512  mode=forward_backward  precision=FP32
  Parameters: 128.6M
  Mean :   149.65 ms
  Std  :     0.22 ms



Running size=small | mode=forward_backward | precision=bf16_mixed

  size=small  ctx=512  mode=forward_backward  precision=BF16 mixed
  Parameters: 128.6M
  Mean :   121.13 ms
  Std  :     4.84 ms



Running size=medium | mode=forward | precision=fp32

  size=medium  ctx=512  mode=forward  precision=FP32
  Parameters: 423.2M
  Mean :   134.68 ms
  Std  :     0.21 ms



Running size=medium | mode=forward | precision=bf16_mixed

  size=medium  ctx=512  mode=forward  precision=BF16 mixed
  Parameters: 423.2M
  Mean :    74.85 ms
  Std  :     1.34 ms



Running size=medium | mode=backward | precision=fp32

  size=medium  ctx=512  mode=backward  precision=FP32
  Parameters: 423.2M
  Mean :   411.13 ms
  Std  :     0.19 ms



Running size=medium | mode=backward | precision=bf16_mixed

  size=medium  ctx=512  mode=backward  precision=BF16 mixed
  Parameters: 423.2M
  Mean :   190.44 ms
  Std  :     4.33 ms



Running size=medium | mode=forward_backward | precision=fp32

  size=medium  ctx=512  mode=forward_backward  precision=FP32
  Parameters: 423.2M
  Mean :   447.97 ms
  Std  :     0.49 ms



Running size=medium | mode=forward_backward | precision=bf16_mixed

  size=medium  ctx=512  mode=forward_backward  precision=BF16 mixed
  Parameters: 423.2M
  Mean :   231.63 ms
  Std  :     2.53 ms



Running size=large | mode=forward | precision=fp32

  size=large  ctx=512  mode=forward  precision=FP32
  Parameters: 969.4M
  Mean :   280.32 ms
  Std  :     0.12 ms



Running size=large | mode=forward | precision=bf16_mixed

  size=large  ctx=512  mode=forward  precision=BF16 mixed
  Parameters: 969.4M
  Mean :   114.26 ms
  Std  :     4.37 ms



Running size=large | mode=backward | precision=fp32

  size=large  ctx=512  mode=backward  precision=FP32
  Parameters: 969.4M
  Mean :   873.62 ms
  Std  :     0.36 ms



Running size=large | mode=backward | precision=bf16_mixed

  size=large  ctx=512  mode=backward  precision=BF16 mixed
  Parameters: 969.4M
  Mean :   291.95 ms
  Std  :     2.88 ms



Running size=large | mode=forward_backward | precision=fp32

  size=large  ctx=512  mode=forward_backward  precision=FP32
  Parameters: 969.4M
  Mean :   961.81 ms
  Std  :     0.36 ms



Running size=large | mode=forward_backward | precision=bf16_mixed

  size=large  ctx=512  mode=forward_backward  precision=BF16 mixed
  Parameters: 969.4M
  Mean :   378.09 ms
  Std  :     1.28 ms



Running size=xl | mode=forward | precision=fp32

  size=xl  ctx=512  mode=forward  precision=FP32
  Parameters: 1998.2M
  Mean :   565.06 ms
  Std  :     0.33 ms



Running size=xl | mode=forward | precision=bf16_mixed

  size=xl  ctx=512  mode=forward  precision=BF16 mixed
  Parameters: 1998.2M
  Mean :   147.81 ms
  Std  :     1.99 ms



Running size=xl | mode=backward | precision=fp32

  size=xl  ctx=512  mode=backward  precision=FP32
  Parameters: 1998.2M
  Mean :  1731.81 ms
  Std  :     0.65 ms



Running size=xl | mode=backward | precision=bf16_mixed

  size=xl  ctx=512  mode=backward  precision=BF16 mixed
  Parameters: 1998.2M
  Mean :   453.97 ms
  Std  :     3.26 ms



Running size=xl | mode=forward_backward | precision=fp32

  size=xl  ctx=512  mode=forward_backward  precision=FP32
  Parameters: 1998.2M
  Mean :  1902.54 ms
  Std  :     0.78 ms



Running size=xl | mode=forward_backward | precision=bf16_mixed

  size=xl  ctx=512  mode=forward_backward  precision=BF16 mixed
  Parameters: 1998.2M
  Mean :   629.23 ms
  Std  :     6.78 ms



Running size=2.7B | mode=forward | precision=fp32

  size=2.7B  ctx=512  mode=forward  precision=FP32
  Parameters: 3406.8M
  Mean :   846.26 ms
  Std  :     0.55 ms



Running size=2.7B | mode=forward | precision=bf16_mixed

  size=2.7B  ctx=512  mode=forward  precision=BF16 mixed
  Parameters: 3406.8M
  Mean :   151.29 ms
  Std  :     0.12 ms



Running size=2.7B | mode=backward | precision=fp32

  size=2.7B  ctx=512  mode=backward  precision=FP32
  Parameters: 3406.8M
  Mean :  2587.05 ms
  Std  :     1.35 ms



Running size=2.7B | mode=backward | precision=bf16_mixed

  size=2.7B  ctx=512  mode=backward  precision=BF16 mixed
  Parameters: 3406.8M
  Mean :   478.16 ms
  Std  :     0.33 ms



Running size=2.7B | mode=forward_backward | precision=fp32

  size=2.7B  ctx=512  mode=forward_backward  precision=FP32
  Parameters: 3406.8M
  Mean :  2876.66 ms
  Std  :     0.41 ms



Running size=2.7B | mode=forward_backward | precision=bf16_mixed

  size=2.7B  ctx=512  mode=forward_backward  precision=BF16 mixed
  Parameters: 3406.8M
  Mean :   765.29 ms
  Std  :     0.38 ms

      size              mode   precision  params_m  mean_ms  std_ms status
0    small           forward        fp32     128.6    58.49   42.75     ok
1    small           forward  bf16_mixed     128.6    36.76    0.38     ok
2    small          backward        fp32     128.6   137.94    0.19     ok
3    small          backward  bf16_mixed     128.6    93.01    2.86     ok
4    small  forward_backward        fp32     128.6   149.65    0.22     ok
5    small  forward_backward  bf16_mixed     128.6   121.13    4.84     ok
6   medium           forward        fp32     423.2   134.68    0.21     ok
7   medium           forward  bf16_mixed     423.2    74.85    1.34     ok
8   medium          backward        fp32     423.2   411.13    0.19     ok
9   medium          backward  bf16_mixed     423.2   190.44    4.33     ok
10  medium  forward_backward        fp32     423.2   447.97    0.49     ok
11  medium  forward_backward  bf16_mixed     423.2   231.63    2.53     ok
12   large           forward        fp32     969.4   280.32    0.12     ok
13   large           forward  bf16_mixed     969.4   114.26    4.37     ok
14   large          backward        fp32     969.4   873.62    0.36     ok
15   large          backward  bf16_mixed     969.4   291.95    2.88     ok
16   large  forward_backward        fp32     969.4   961.81    0.36     ok
17   large  forward_backward  bf16_mixed     969.4   378.09    1.28     ok
18      xl           forward        fp32    1998.2   565.06    0.33     ok
19      xl           forward  bf16_mixed    1998.2   147.81    1.99     ok
20      xl          backward        fp32    1998.2  1731.81    0.65     ok
21      xl          backward  bf16_mixed    1998.2   453.97    3.26     ok
22      xl  forward_backward        fp32    1998.2  1902.54    0.78     ok
23      xl  forward_backward  bf16_mixed    1998.2   629.23    6.78     ok
24    2.7B           forward        fp32    3406.8   846.26    0.55     ok
25    2.7B           forward  bf16_mixed    3406.8   151.29    0.12     ok
26    2.7B          backward        fp32    3406.8  2587.05    1.35     ok
27    2.7B          backward  bf16_mixed    3406.8   478.16    0.33     ok
28    2.7B  forward_backward        fp32    3406.8  2876.66    0.41     ok
29    2.7B  forward_backward  bf16_mixed    3406.8   765.29    0.38     ok

## Part 4: Memory Profiling

#### Full precision 2.7b profiling

In [7]:
import os
import subprocess
import pandas as pd
import re

size = "2.7B"
contexts = [128, 256, 512]
modes = ["forward", "forward_backward"]   # inference only vs full training step

os.makedirs("memory_snapshots", exist_ok=True)

results = []

for ctx in contexts:
    for mode in modes:
        snapshot_file = f"memory_snapshots/{size}_ctx{ctx}_{mode}.pickle"

        cmd = f"""
        uv run python ./student/memory_profiling.py \
            --size "{size}" \
            --context_length {ctx} \
            --mode {mode} \
            --warmup_steps 5 \
            --profile_memory \
            --snapshot_file "{snapshot_file}"
        """

        print(f"\nRunning size={size} | ctx={ctx} | mode={mode}")

        try:
            output = subprocess.check_output(
                cmd,
                shell=True,
                text=True,
                stderr=subprocess.STDOUT
            )
            print(output)

            peak_match = re.search(r"Peak memory allocated:\s*([\d\.]+)\s*MB", output)
            param_match = re.search(r"Parameters:\s*([\d\.]+)M", output)

            results.append({
                "size": size,
                "context_length": ctx,
                "mode": mode,
                "params_m": float(param_match.group(1)) if param_match else None,
                "peak_memory_mb": float(peak_match.group(1)) if peak_match else None,
                "snapshot_file": snapshot_file,
                "status": "ok",
            })

        except subprocess.CalledProcessError as e:
            print(e.output)
            results.append({
                "size": size,
                "context_length": ctx,
                "mode": mode,
                "params_m": None,
                "peak_memory_mb": None,
                "snapshot_file": snapshot_file,
                "status": "failed/OOM",
            })

df = pd.DataFrame(results)
df

Running size=2.7B | ctx=128 | mode=forward

  size=2.7B  ctx=128  mode=forward  precision=FP32
  Parameters: 3406.8M
  Warming up for 5 step(s)...
  Starting memory recorder...
  Snapshot saved to: memory_snapshots/2.7B_ctx128_forward.pickle
  Peak memory allocated: 13212.8 MB


Running size=2.7B | ctx=128 | mode=forward_backward

  size=2.7B  ctx=128  mode=forward_backward  precision=FP32
  Parameters: 3406.8M
  Warming up for 5 step(s)...
  Starting memory recorder...
  Snapshot saved to: memory_snapshots/2.7B_ctx128_forward_backward.pickle
  Peak memory allocated: 52649.5 MB


Running size=2.7B | ctx=256 | mode=forward

  size=2.7B  ctx=256  mode=forward  precision=FP32
  Parameters: 3406.8M
  Warming up for 5 step(s)...
  Starting memory recorder...
  Snapshot saved to: memory_snapshots/2.7B_ctx256_forward.pickle
  Peak memory allocated: 13311.0 MB


Running size=2.7B | ctx=256 | mode=forward_backward

  size=2.7B  ctx=256  mode=forward_backward  precision=FP32
  Parameters: 3406.8M
  Warming up for 5 step(s)...
  Starting memory recorder...
  Snapshot saved to: memory_snapshots/2.7B_ctx256_forward_backward.pickle
  Peak memory allocated: 52669.6 MB


Running size=2.7B | ctx=512 | mode=forward

  size=2.7B  ctx=512  mode=forward  precision=FP32
  Parameters: 3406.8M
  Warming up for 5 step(s)...
  Starting memory recorder...
  Snapshot saved to: memory_snapshots/2.7B_ctx512_forward.pickle
  Peak memory allocated: 13745.5 MB


Running size=2.7B | ctx=512 | mode=forward_backward

  size=2.7B  ctx=512  mode=forward_backward  precision=FP32
  Parameters: 3406.8M
  Warming up for 5 step(s)...
  Starting memory recorder...
  Snapshot saved to: memory_snapshots/2.7B_ctx512_forward_backward.pickle
  Peak memory allocated: 67121.3 MB

,size,context_length,mode,params_m,peak_memory_mb,snapshot_file,status
0,2.7B,128,forward,3406.8,13212.8,memory_snapshots/2.7B_ctx128_forward.pickle,ok
1,2.7B,128,forward_backward,3406.8,52649.5,memory_snapshots/2.7B_ctx128_forward_backward....,ok
2,2.7B,256,forward,3406.8,13311.0,memory_snapshots/2.7B_ctx256_forward.pickle,ok
3,2.7B,256,forward_backward,3406.8,52669.6,memory_snapshots/2.7B_ctx256_forward_backward....,ok
4,2.7B,512,forward,3406.8,13745.5,memory_snapshots/2.7B_ctx512_forward.pickle,ok
5,2.7B,512,forward_backward,3406.8,67121.3,memory_snapshots/2.7B_ctx512_forward_backward....,ok

In [8]:
report = df.pivot_table(
    index="context_length",
    columns="mode",
    values="peak_memory_mb",
    aggfunc="first"
).reset_index()

report.columns.name = None
report = report.rename(columns={
    "forward": "forward_peak_mb",
    "forward_backward": "training_step_peak_mb"
})

report

   context_length  forward_peak_mb  training_step_peak_mb
0             128          13212.8                52649.5
1             256          13311.0                52669.6
2             512          13745.5                67121.3

In [8]:
!zip -r memory_snapshots.zip memory_snapshots/

  adding: memory_snapshots/ (stored 0%)
  adding: memory_snapshots/2.7B_ctx256_forward_bf16_mixed.pickle (deflated 95%)
  adding: memory_snapshots/2.7B_ctx512_forward_bf16_mixed.pickle (deflated 95%)
  adding: memory_snapshots/2.7B_ctx128_forward_fp32.pickle (deflated 95%)
  adding: memory_snapshots/2.7B_ctx512_forward_backward_bf16_mixed.pickle (deflated 94%)
  adding: memory_snapshots/2.7B_ctx256_forward_backward_fp32.pickle (deflated 94%)
  adding: memory_snapshots/2.7B_ctx256_forward_backward_bf16_mixed.pickle (deflated 94%)
  adding: memory_snapshots/2.7B_ctx512_forward_backward_fp32.pickle (deflated 94%)
  adding: memory_snapshots/2.7B_ctx256_forward_fp32.pickle (deflated 95%)
  adding: memory_snapshots/2.7B_ctx512_forward_fp32.pickle (deflated 95%)
  adding: memory_snapshots/2.7B_ctx128_forward_bf16_mixed.pickle (deflated 95%)
  adding: memory_snapshots/2.7B_ctx128_forward_backward_fp32.pickle (deflated 95%)
  adding: memory_snapshots/2.7B_ctx128_forward_backward_bf16_mixed.pickle (deflated 94%)

#### mixed precision 2.7 b memory profiling

In [6]:
import os
import subprocess
import pandas as pd
import re

size = "2.7B"
contexts = [128, 256, 512]
modes = ["forward", "forward_backward"]
precisions = [
    ("fp32", False),
    ("bf16_mixed", True),
]

os.makedirs("memory_snapshots", exist_ok=True)

results = []

for precision_name, use_mixed in precisions:
    for ctx in contexts:
        for mode in modes:
            snapshot_file = f"memory_snapshots/{size}_ctx{ctx}_{mode}_{precision_name}.pickle"

            cmd = f"""
            uv run python ./student/memory_profiling.py \
                --size "{size}" \
                --context_length {ctx} \
                --mode {mode} \
                --warmup_steps 5 \
                --profile_memory \
                --snapshot_file "{snapshot_file}" \
                {"--mixed_precision" if use_mixed else ""}
            """

            print(f"\nRunning size={size} | ctx={ctx} | mode={mode} | precision={precision_name}")

            try:
                output = subprocess.check_output(
                    cmd,
                    shell=True,
                    text=True,
                    stderr=subprocess.STDOUT
                )
                print(output)

                peak_match = re.search(r"Peak memory allocated:\s*([\d\.]+)\s*MB", output)
                param_match = re.search(r"Parameters:\s*([\d\.]+)M", output)

                results.append({
                    "size": size,
                    "context_length": ctx,
                    "mode": mode,
                    "precision": precision_name,
                    "params_m": float(param_match.group(1)) if param_match else None,
                    "peak_memory_mb": float(peak_match.group(1)) if peak_match else None,
                    "snapshot_file": snapshot_file,
                    "status": "ok",
                })

            except subprocess.CalledProcessError as e:
                print(e.output)
                results.append({
                    "size": size,
                    "context_length": ctx,
                    "mode": mode,
                    "precision": precision_name,
                    "params_m": None,
                    "peak_memory_mb": None,
                    "snapshot_file": snapshot_file,
                    "status": "failed/OOM",
                })

df = pd.DataFrame(results)
df

Running size=2.7B | ctx=128 | mode=forward | precision=fp32
Using CPython 3.12.12 interpreter at: /usr/bin/python3
Creating virtual environment at: .venv
Installed 75 packages in 241ms

  size=2.7B  ctx=128  mode=forward  precision=FP32
  Parameters: 3406.8M
  Warming up for 5 step(s)...
  Starting memory recorder...
  Snapshot saved to: memory_snapshots/2.7B_ctx128_forward_fp32.pickle
  Peak memory allocated: 13212.8 MB


Running size=2.7B | ctx=128 | mode=forward_backward | precision=fp32

  size=2.7B  ctx=128  mode=forward_backward  precision=FP32
  Parameters: 3406.8M
  Warming up for 5 step(s)...
  Starting memory recorder...
  Snapshot saved to: memory_snapshots/2.7B_ctx128_forward_backward_fp32.pickle
  Peak memory allocated: 52649.5 MB


Running size=2.7B | ctx=256 | mode=forward | precision=fp32

  size=2.7B  ctx=256  mode=forward  precision=FP32
  Parameters: 3406.8M
  Warming up for 5 step(s)...
  Starting memory recorder...
  Snapshot saved to: memory_snapshots/2.7B_ctx256_forward_fp32.pickle
  Peak memory allocated: 13311.0 MB


Running size=2.7B | ctx=256 | mode=forward_backward | precision=fp32

  size=2.7B  ctx=256  mode=forward_backward  precision=FP32
  Parameters: 3406.8M
  Warming up for 5 step(s)...
  Starting memory recorder...
  Snapshot saved to: memory_snapshots/2.7B_ctx256_forward_backward_fp32.pickle
  Peak memory allocated: 52669.6 MB


Running size=2.7B | ctx=512 | mode=forward | precision=fp32

  size=2.7B  ctx=512  mode=forward  precision=FP32
  Parameters: 3406.8M
  Warming up for 5 step(s)...
  Starting memory recorder...
  Snapshot saved to: memory_snapshots/2.7B_ctx512_forward_fp32.pickle
  Peak memory allocated: 13745.5 MB


Running size=2.7B | ctx=512 | mode=forward_backward | precision=fp32

  size=2.7B  ctx=512  mode=forward_backward  precision=FP32
  Parameters: 3406.8M
  Warming up for 5 step(s)...
  Starting memory recorder...
  Snapshot saved to: memory_snapshots/2.7B_ctx512_forward_backward_fp32.pickle
  Peak memory allocated: 67121.3 MB


Running size=2.7B | ctx=128 | mode=forward | precision=bf16_mixed

  size=2.7B  ctx=128  mode=forward  precision=BF16 mixed
  Parameters: 3406.8M
  Warming up for 5 step(s)...
  Starting memory recorder...
  Snapshot saved to: memory_snapshots/2.7B_ctx128_forward_bf16_mixed.pickle
  Peak memory allocated: 19599.1 MB


Running size=2.7B | ctx=128 | mode=forward_backward | precision=bf16_mixed

  size=2.7B  ctx=128  mode=forward_backward  precision=BF16 mixed
  Parameters: 3406.8M
  Warming up for 5 step(s)...
  Starting memory recorder...
  Snapshot saved to: memory_snapshots/2.7B_ctx128_forward_backward_bf16_mixed.pickle
  Peak memory allocated: 52639.2 MB


Running size=2.7B | ctx=256 | mode=forward | precision=bf16_mixed

  size=2.7B  ctx=256  mode=forward  precision=BF16 mixed
  Parameters: 3406.8M
  Warming up for 5 step(s)...
  Starting memory recorder...
  Snapshot saved to: memory_snapshots/2.7B_ctx256_forward_bf16_mixed.pickle
  Peak memory allocated: 19616.2 MB


Running size=2.7B | ctx=256 | mode=forward_backward | precision=bf16_mixed

  size=2.7B  ctx=256  mode=forward_backward  precision=BF16 mixed
  Parameters: 3406.8M
  Warming up for 5 step(s)...
  Starting memory recorder...
  Snapshot saved to: memory_snapshots/2.7B_ctx256_forward_backward_bf16_mixed.pickle
  Peak memory allocated: 53337.9 MB


Running size=2.7B | ctx=512 | mode=forward | precision=bf16_mixed

  size=2.7B  ctx=512  mode=forward  precision=BF16 mixed
  Parameters: 3406.8M
  Warming up for 5 step(s)...
  Starting memory recorder...
  Snapshot saved to: memory_snapshots/2.7B_ctx512_forward_bf16_mixed.pickle
  Peak memory allocated: 19847.5 MB


Running size=2.7B | ctx=512 | mode=forward_backward | precision=bf16_mixed

  size=2.7B  ctx=512  mode=forward_backward  precision=BF16 mixed
  Parameters: 3406.8M
  Warming up for 5 step(s)...
  Starting memory recorder...
  Snapshot saved to: memory_snapshots/2.7B_ctx512_forward_backward_bf16_mixed.pickle
  Peak memory allocated: 64186.0 MB

,size,context_length,mode,precision,params_m,peak_memory_mb,snapshot_file,status
0,2.7B,128,forward,fp32,3406.8,13212.8,memory_snapshots/2.7B_ctx128_forward_fp32.pickle,ok
1,2.7B,128,forward_backward,fp32,3406.8,52649.5,memory_snapshots/2.7B_ctx128_forward_backward_...,ok
2,2.7B,256,forward,fp32,3406.8,13311.0,memory_snapshots/2.7B_ctx256_forward_fp32.pickle,ok
3,2.7B,256,forward_backward,fp32,3406.8,52669.6,memory_snapshots/2.7B_ctx256_forward_backward_...,ok
4,2.7B,512,forward,fp32,3406.8,13745.5,memory_snapshots/2.7B_ctx512_forward_fp32.pickle,ok
5,2.7B,512,forward_backward,fp32,3406.8,67121.3,memory_snapshots/2.7B_ctx512_forward_backward_...,ok
6,2.7B,128,forward,bf16_mixed,3406.8,19599.1,memory_snapshots/2.7B_ctx128_forward_bf16_mixe...,ok
7,2.7B,128,forward_backward,bf16_mixed,3406.8,52639.2,memory_snapshots/2.7B_ctx128_forward_backward_...,ok
8,2.7B,256,forward,bf16_mixed,3406.8,19616.2,memory_snapshots/2.7B_ctx256_forward_bf16_mixe...,ok
9,2.7B,256,forward_backward,bf16_mixed,3406.8,53337.9,memory_snapshots/2.7B_ctx256_forward_backward_...,ok
10,2.7B,512,forward,bf16_mixed,3406.8,19847.5,memory_snapshots/2.7B_ctx512_forward_bf16_mixe...,ok
11,2.7B,512,forward_backward,bf16_mixed,3406.8,64186.0,memory_snapshots/2.7B_ctx512_forward_backward_...,ok

In [7]:
comparison = df.pivot_table(
    index=["context_length", "mode"],
    columns="precision",
    values="peak_memory_mb",
    aggfunc="first"
).reset_index()

comparison["absolute_reduction_mb"] = comparison["fp32"] - comparison["bf16_mixed"]
comparison["percent_reduction"] = 100 * (comparison["fp32"] - comparison["bf16_mixed"]) / comparison["fp32"]

comparison

precision,context_length,mode,bf16_mixed,fp32,absolute_reduction_mb,percent_reduction
0,128,forward,19599.1,13212.8,-6386.3,-48.334191
1,128,forward_backward,52639.2,52649.5,10.3,0.019563
2,256,forward,19616.2,13311.0,-6305.2,-47.368342
3,256,forward_backward,53337.9,52669.6,-668.3,-1.268853
4,512,forward,19847.5,13745.5,-6102.0,-44.392710
5,512,forward_backward,64186.0,67121.3,2935.3,4.373127

## Part 5 : Benchmarking Attention

### Benchmarking Pytorch attention

In [7]:
import subprocess

cmd = """
uv run python ./student/benchmark_pytorch_attention.py \
    --warmup 5 \
    --n_steps 100
"""

output = subprocess.check_output(
    cmd,
    shell=True,
    text=True,
    stderr=subprocess.STDOUT
)

print(output)

Using CPython 3.12.12 interpreter at: /usr/bin/python3
Creating virtual environment at: .venv
Installed 75 packages in 266ms

Attention benchmark  |  batch=8  device=cuda  warmup=5  steps=100

  d_model=  16  seq_len=   256 ...  fwd=0.22ms  mem=13.1MB  bwd=1.29ms
  d_model=  16  seq_len=  1024 ...  fwd=0.57ms  mem=84.3MB  bwd=2.00ms
  d_model=  16  seq_len=  4096 ...  fwd=5.99ms  mem=1056.6MB  bwd=21.61ms
  d_model=  16  seq_len=  8192 ...  fwd=22.25ms  mem=4145.0MB  bwd=79.52ms
  d_model=  16  seq_len= 16384 ...  fwd=88.00ms  mem=16465.8MB  bwd=321.05ms
  d_model=  32  seq_len=   256 ...  fwd=0.22ms  mem=22.3MB  bwd=0.91ms
  d_model=  32  seq_len=  1024 ...  fwd=0.52ms  mem=88.3MB  bwd=1.86ms
  d_model=  32  seq_len=  4096 ...  fwd=6.22ms  mem=1072.6MB  bwd=22.05ms
  d_model=  32  seq_len=  8192 ...  fwd=23.18ms  mem=4177.0MB  bwd=81.24ms
  d_model=  32  seq_len= 16384 ...  fwd=91.59ms  mem=16529.8MB  bwd=322.59ms
  d_model=  64  seq_len=   256 ...  fwd=0.21ms  mem=24.3MB  bwd=0.91ms
  d_model=  64  seq_len=  1024 ...  fwd=0.55ms  mem=96.3MB  bwd=1.92ms
  d_model=  64  seq_len=  4096 ...  fwd=6.67ms  mem=1104.6MB  bwd=22.97ms
  d_model=  64  seq_len=  8192 ...  fwd=24.98ms  mem=4241.0MB  bwd=84.92ms
  d_model=  64  seq_len= 16384 ...  fwd=98.86ms  mem=16657.8MB  bwd=337.14ms
  d_model= 128  seq_len=   256 ...  fwd=0.21ms  mem=28.3MB  bwd=1.04ms
  d_model= 128  seq_len=  1024 ...  fwd=0.61ms  mem=112.3MB  bwd=2.06ms
  d_model= 128  seq_len=  4096 ...  fwd=7.54ms  mem=1168.6MB  bwd=24.73ms
  d_model= 128  seq_len=  8192 ...  fwd=28.44ms  mem=4369.0MB  bwd=91.98ms
  d_model= 128  seq_len= 16384 ...  OOM (bwd)

=================================================================
Results
=================================================================
 d_model  seq_len fwd_ms mem_before_bwd_mb bwd_ms
      16      256   0.22              13.1   1.29
      16     1024   0.57              84.3   2.00
      16     4096   5.99            1056.6  21.61
      16     8192  22.25            4145.0  79.52
      16    16384  88.00           16465.8 321.05
      32      256   0.22              22.3   0.91
      32     1024   0.52              88.3   1.86
      32     4096   6.22            1072.6  22.05
      32     8192  23.18            4177.0  81.24
      32    16384  91.59           16529.8 322.59
      64      256   0.21              24.3   0.91
      64     1024   0.55              96.3   1.92
      64     4096   6.67            1104.6  22.97
      64     8192  24.98            4241.0  84.92
      64    16384  98.86           16657.8 337.14
     128      256   0.21              28.3   1.04
     128     1024   0.61             112.3   2.06
     128     4096   7.54            1168.6  24.73
     128     8192  28.44            4369.0  91.98
     128    16384 112.62           16913.8    OOM

Saved to attention_benchmark_results.csv

Rerun

In [16]:
import subprocess

cmd = """
uv run python ./student/benchmark_pytorch_attention.py \
    --warmup 5 \
    --n_steps 100
"""

output = subprocess.check_output(
    cmd,
    shell=True,
    text=True,
    stderr=subprocess.STDOUT
)

print(output)

Attention benchmark  |  batch=8  device=cuda  warmup=5  steps=100

  d_model=  16  seq_len=   256 ...  fwd=0.22ms  mem=13.1MB  bwd=1.27ms
  d_model=  16  seq_len=  1024 ...  fwd=0.51ms  mem=84.3MB  bwd=1.83ms
  d_model=  16  seq_len=  4096 ...  fwd=5.99ms  mem=1056.6MB  bwd=21.55ms
  d_model=  16  seq_len=  8192 ...  fwd=22.27ms  mem=4145.0MB  bwd=79.52ms
  d_model=  16  seq_len= 16384 ...  fwd=88.01ms  mem=16465.8MB  bwd=321.09ms
  d_model=  32  seq_len=   256 ...  fwd=0.21ms  mem=22.3MB  bwd=0.92ms
  d_model=  32  seq_len=  1024 ...  fwd=0.52ms  mem=88.3MB  bwd=1.86ms
  d_model=  32  seq_len=  4096 ...  fwd=6.21ms  mem=1072.6MB  bwd=22.04ms
  d_model=  32  seq_len=  8192 ...  fwd=23.18ms  mem=4177.0MB  bwd=81.31ms
  d_model=  32  seq_len= 16384 ...  fwd=91.59ms  mem=16529.8MB  bwd=322.61ms
  d_model=  64  seq_len=   256 ...  fwd=0.21ms  mem=24.3MB  bwd=0.93ms
  d_model=  64  seq_len=  1024 ...  fwd=0.55ms  mem=96.3MB  bwd=1.92ms
  d_model=  64  seq_len=  4096 ...  fwd=6.66ms  mem=1104.6MB  bwd=23.00ms
  d_model=  64  seq_len=  8192 ...  fwd=24.98ms  mem=4241.0MB  bwd=84.97ms
  d_model=  64  seq_len= 16384 ...  fwd=98.84ms  mem=16657.8MB  bwd=337.15ms
  d_model= 128  seq_len=   256 ...  fwd=0.21ms  mem=28.3MB  bwd=0.93ms
  d_model= 128  seq_len=  1024 ...  fwd=0.61ms  mem=112.3MB  bwd=2.05ms
  d_model= 128  seq_len=  4096 ...  fwd=7.53ms  mem=1168.6MB  bwd=24.75ms
  d_model= 128  seq_len=  8192 ...  fwd=28.46ms  mem=4369.0MB  bwd=91.98ms
  d_model= 128  seq_len= 16384 ...  OOM (bwd)

=================================================================
Results
=================================================================
 d_model  seq_len fwd_ms mem_before_bwd_mb bwd_ms
      16      256   0.22              13.1   1.27
      16     1024   0.51              84.3   1.83
      16     4096   5.99            1056.6  21.55
      16     8192  22.27            4145.0  79.52
      16    16384  88.01           16465.8 321.09
      32      256   0.21              22.3   0.92
      32     1024   0.52              88.3   1.86
      32     4096   6.21            1072.6  22.04
      32     8192  23.18            4177.0  81.31
      32    16384  91.59           16529.8 322.61
      64      256   0.21              24.3   0.93
      64     1024   0.55              96.3   1.92
      64     4096   6.66            1104.6  23.00
      64     8192  24.98            4241.0  84.97
      64    16384  98.84           16657.8 337.15
     128      256   0.21              28.3   0.93
     128     1024   0.61             112.3   2.05
     128     4096   7.53            1168.6  24.75
     128     8192  28.46            4369.0  91.98
     128    16384 112.61           16913.8    OOM

Saved to attention_benchmark_results.csv

### JIT Attention Benchmarking

In [15]:
import subprocess

cmd = """
uv run python ./student/benchmark_jit_attention.py \
    --warmup 5 \
    --n_steps 100
"""

output = subprocess.check_output(
    cmd,
    shell=True,
    text=True,
    stderr=subprocess.STDOUT
)

print(output)

Using CPython 3.12.12 interpreter at: /usr/bin/python3
Creating virtual environment at: .venv
Installed 75 packages in 233ms

Attention benchmark (vanilla vs compiled)  |  batch=8  device=cuda  warmup=5  steps=100

  d_model=  16  seq_len=   256
    [vanilla] ...  fwd=0.22ms  mem=13.0MB  bwd=1.42ms
    [compiled] ...  /content/llmr-a2/.venv/lib/python3.12/site-packages/torch/_inductor/compile_fx.py:194: UserWarning: TensorFloat32 tensor cores for float32 matrix multiplication available but not enabled. Consider setting `torch.set_float32_matmul_precision('high')` for better performance.
  warnings.warn(
fwd=0.21ms  mem=21.2MB  bwd=12.94ms
  d_model=  16  seq_len=  1024
    [vanilla] ...  fwd=0.51ms  mem=83.8MB  bwd=1.83ms
    [compiled] ...  fwd=0.40ms  mem=83.9MB  bwd=4.71ms
  d_model=  16  seq_len=  4096
    [vanilla] ...  fwd=5.98ms  mem=1054.6MB  bwd=21.56ms
    [compiled] ...  fwd=3.54ms  mem=1054.8MB  bwd=13.51ms
  d_model=  16  seq_len=  8192
    [vanilla] ...  fwd=22.28ms  mem=4141.0MB  bwd=79.53ms
    [compiled] ...  fwd=13.43ms  mem=4141.2MB  bwd=48.70ms
  d_model=  16  seq_len= 16384
    [vanilla] ...  fwd=88.05ms  mem=16457.8MB  bwd=321.10ms
    [compiled] ...  fwd=52.96ms  mem=16458.2MB  bwd=360.22ms
  d_model=  32  seq_len=   256
    [vanilla] ...  fwd=0.21ms  mem=22.0MB  bwd=0.92ms
    [compiled] ...  fwd=0.24ms  mem=22.0MB  bwd=3.03ms
  d_model=  32  seq_len=  1024
    [vanilla] ...  fwd=0.52ms  mem=87.3MB  bwd=1.86ms
    [compiled] ...  fwd=0.44ms  mem=87.4MB  bwd=1.55ms
  d_model=  32  seq_len=  4096
    [vanilla] ...  fwd=6.22ms  mem=1068.6MB  bwd=22.06ms
    [compiled] ...  fwd=4.40ms  mem=1068.8MB  bwd=14.79ms
  d_model=  32  seq_len=  8192
    [vanilla] ...  fwd=23.19ms  mem=4169.0MB  bwd=81.38ms
    [compiled] ...  fwd=15.65ms  mem=4169.2MB  bwd=52.38ms
  d_model=  32  seq_len= 16384
    [vanilla] ...  fwd=91.64ms  mem=16513.8MB  bwd=322.64ms
    [compiled] ...  W0306 18:39:04.412000 4762 torch/_dynamo/convert_frame.py:906] [0/8] torch._dynamo hit config.cache_size_limit (8)
W0306 18:39:04.412000 4762 torch/_dynamo/convert_frame.py:906] [0/8]    function: 'scaled_dot_product_attention' (/content/llmr-a2/./student/benchmark_jit_attention.py:21)
W0306 18:39:04.412000 4762 torch/_dynamo/convert_frame.py:906] [0/8]    last reason: 0/0: tensor 'L['K']' size mismatch at index 1. expected 256, actual 16384
W0306 18:39:04.412000 4762 torch/_dynamo/convert_frame.py:906] [0/8] To log all recompilation reasons, use TORCH_LOGS="recompiles".
W0306 18:39:04.412000 4762 torch/_dynamo/convert_frame.py:906] [0/8] To diagnose recompilation issues, see https://pytorch.org/docs/main/torch.compiler_troubleshooting.html.
fwd=91.73ms  mem=16513.8MB  bwd=322.76ms
  d_model=  64  seq_len=   256
    [vanilla] ...  fwd=0.21ms  mem=23.8MB  bwd=0.91ms
    [compiled] ...  fwd=0.23ms  mem=23.8MB  bwd=1.01ms
  d_model=  64  seq_len=  1024
    [vanilla] ...  fwd=0.55ms  mem=94.3MB  bwd=1.91ms
    [compiled] ...  fwd=0.47ms  mem=94.4MB  bwd=1.56ms
  d_model=  64  seq_len=  4096
    [vanilla] ...  fwd=6.66ms  mem=1096.6MB  bwd=22.98ms
    [compiled] ...  fwd=4.87ms  mem=1096.8MB  bwd=15.78ms
  d_model=  64  seq_len=  8192
    [vanilla] ...  fwd=24.97ms  mem=4225.0MB  bwd=84.93ms
    [compiled] ...  fwd=17.46ms  mem=4225.2MB  bwd=55.99ms
  d_model=  64  seq_len= 16384
    [vanilla] ...  fwd=98.84ms  mem=16625.8MB  bwd=337.18ms
    [compiled] ...  fwd=98.94ms  mem=16625.8MB  bwd=337.30ms
  d_model= 128  seq_len=   256
    [vanilla] ...  fwd=0.21ms  mem=27.3MB  bwd=0.93ms
    [compiled] ...  fwd=0.23ms  mem=27.3MB  bwd=1.05ms
  d_model= 128  seq_len=  1024
    [vanilla] ...  fwd=0.61ms  mem=108.3MB  bwd=2.04ms
    [compiled] ...  fwd=0.53ms  mem=108.4MB  bwd=1.72ms
  d_model= 128  seq_len=  4096
    [vanilla] ...  fwd=7.54ms  mem=1152.6MB  bwd=24.76ms
    [compiled] ...  fwd=5.73ms  mem=1152.8MB  bwd=17.50ms
  d_model= 128  seq_len=  8192
    [vanilla] ...  fwd=28.45ms  mem=4337.0MB  bwd=91.99ms
    [compiled] ...  fwd=20.93ms  mem=4337.2MB  bwd=63.01ms
  d_model= 128  seq_len= 16384
    [vanilla] ...  fwd=112.64ms  mem=16849.8MB  bwd=364.97ms
    [compiled] ...  fwd=112.77ms  mem=16849.8MB  bwd=365.03ms

==========================================================================================
Results — vanilla vs compiled
==========================================================================================
 d_model  seq_len fwd_ms_compiled fwd_ms_vanilla mem_before_bwd_mb_compiled mem_before_bwd_mb_vanilla bwd_ms_compiled bwd_ms_vanilla
      16      256            0.21           0.22                       21.2                      13.0           12.94           1.42
      16     1024            0.40           0.51                       83.9                      83.8            4.71           1.83
      16     4096            3.54           5.98                     1054.8                    1054.6           13.51          21.56
      16     8192           13.43          22.28                     4141.2                    4141.0           48.70          79.53
      16    16384           52.96          88.05                    16458.2                   16457.8          360.22         321.10
      32      256            0.24           0.21                       22.0                      22.0            3.03           0.92
      32     1024            0.44           0.52                       87.4                      87.3            1.55           1.86
      32     4096            4.40           6.22                     1068.8                    1068.6           14.79          22.06
      32     8192           15.65          23.19                     4169.2                    4169.0           52.38          81.38
      32    16384           91.73          91.64                    16513.8                   16513.8          322.76         322.64
      64      256            0.23           0.21                       23.8                      23.8            1.01           0.91
      64     1024            0.47           0.55                       94.4                      94.3            1.56           1.91
      64     4096            4.87           6.66                     1096.8                    1096.6           15.78          22.98
      64     8192           17.46          24.97                     4225.2                    4225.0           55.99          84.93
      64    16384           98.94          98.84                    16625.8                   16625.8          337.30         337.18
     128      256            0.23           0.21                       27.3                      27.3            1.05           0.93
     128     1024            0.53           0.61                      108.4                     108.3            1.72           2.04
     128     4096            5.73           7.54                     1152.8                    1152.6           17.50          24.76
     128     8192           20.93          28.45                     4337.2                    4337.0           63.01          91.99
     128    16384          112.77         112.64                    16849.8                   16849.8          365.03         364.97

Saved to attention_compile_results_long.csv and attention_compile_results_pivot.csv

## Part 6 : Flash Attention Benchmarking

### original

In [6]:
import subprocess

cmd = """
uv run python ./student/flash_attention_benchmarking.py
"""

output = subprocess.check_output(
    cmd,
    shell=True,
    text=True,
    stderr=subprocess.STDOUT
)

print(output)

Using CPython 3.12.12 interpreter at: /usr/bin/python3
Creating virtual environment at: .venv
Installed 75 packages in 234ms
GPU: NVIDIA A100-SXM4-80GB
PyTorch: 2.6.0+cu124
Triton:  3.2.0

Running benchmark sweep...
  dtype=bf16  seq=   128  d= 16  /content/llmr-a2/.venv/lib/python3.12/site-packages/torch/_inductor/compile_fx.py:194: UserWarning: TensorFloat32 tensor cores for float32 matrix multiplication available but not enabled. Consider setting `torch.set_float32_matmul_precision('high')` for better performance.
  warnings.warn(
fwd  flash=0.026ms  pt=0.107ms  |  bwd  flash=0.490ms  pt=0.245ms  |  e2e  flash=0.734ms  pt=0.567ms
  dtype=bf16  seq=   128  d= 32  fwd  flash=0.023ms  pt=0.105ms  |  bwd  flash=0.568ms  pt=0.317ms  |  e2e  flash=0.816ms  pt=0.607ms
  dtype=bf16  seq=   128  d= 64  fwd  flash=0.037ms  pt=0.117ms  |  bwd  flash=0.572ms  pt=0.236ms  |  e2e  flash=0.842ms  pt=0.576ms
  dtype=bf16  seq=   128  d=128  fwd  flash=0.028ms  pt=0.112ms  |  bwd  flash=0.554ms  pt=0.243ms  |  e2e  flash=0.797ms  pt=0.600ms
  dtype=bf16  seq=   256  d= 16  fwd  flash=0.041ms  pt=0.116ms  |  bwd  flash=0.604ms  pt=0.261ms  |  e2e  flash=0.855ms  pt=0.595ms
  dtype=bf16  seq=   256  d= 32  fwd  flash=0.028ms  pt=0.109ms  |  bwd  flash=0.615ms  pt=0.383ms  |  e2e  flash=0.864ms  pt=0.665ms
  dtype=bf16  seq=   256  d= 64  fwd  flash=0.024ms  pt=0.115ms  |  bwd  flash=0.707ms  pt=0.260ms  |  e2e  flash=0.909ms  pt=0.604ms
  dtype=bf16  seq=   256  d=128  fwd  flash=0.028ms  pt=0.116ms  |  bwd  flash=0.627ms  pt=0.258ms  |  e2e  flash=0.864ms  pt=0.621ms
  dtype=bf16  seq=   512  d= 16  fwd  flash=0.042ms  pt=0.115ms  |  bwd  flash=0.607ms  pt=0.243ms  |  e2e  flash=0.852ms  pt=0.581ms
  dtype=bf16  seq=   512  d= 32  fwd  flash=0.032ms  pt=0.133ms  |  bwd  flash=0.623ms  pt=0.246ms  |  e2e  flash=0.859ms  pt=0.588ms
  dtype=bf16  seq=   512  d= 64  fwd  flash=0.029ms  pt=0.119ms  |  bwd  flash=0.617ms  pt=0.255ms  |  e2e  flash=0.864ms  pt=0.595ms
  dtype=bf16  seq=   512  d=128  fwd  flash=0.041ms  pt=0.103ms  |  bwd  flash=0.683ms  pt=0.393ms  |  e2e  flash=0.928ms  pt=0.676ms
  dtype=bf16  seq=  1024  d= 16  fwd  flash=0.027ms  pt=0.115ms  |  bwd  flash=0.733ms  pt=0.400ms  |  e2e  flash=0.953ms  pt=0.693ms
  dtype=bf16  seq=  1024  d= 32  fwd  flash=0.028ms  pt=0.117ms  |  bwd  flash=0.737ms  pt=0.275ms  |  e2e  flash=0.952ms  pt=0.595ms
  dtype=bf16  seq=  1024  d= 64  fwd  flash=0.030ms  pt=0.111ms  |  bwd  flash=0.629ms  pt=0.276ms  |  e2e  flash=0.882ms  pt=0.585ms
  dtype=bf16  seq=  1024  d=128  fwd  flash=0.046ms  pt=0.108ms  |  bwd  flash=0.621ms  pt=0.240ms  |  e2e  flash=0.849ms  pt=0.584ms
  dtype=bf16  seq=  2048  d= 16  fwd  flash=0.038ms  pt=0.131ms  |  bwd  flash=0.624ms  pt=0.246ms  |  e2e  flash=0.861ms  pt=0.591ms
  dtype=bf16  seq=  2048  d= 32  fwd  flash=0.039ms  pt=0.131ms  |  bwd  flash=0.622ms  pt=0.235ms  |  e2e  flash=0.866ms  pt=0.549ms
  dtype=bf16  seq=  2048  d= 64  fwd  flash=0.050ms  pt=0.134ms  |  bwd  flash=0.603ms  pt=0.242ms  |  e2e  flash=0.865ms  pt=0.582ms
  dtype=bf16  seq=  2048  d=128  fwd  flash=0.077ms  pt=0.140ms  |  bwd  flash=0.640ms  pt=0.254ms  |  e2e  flash=0.879ms  pt=0.607ms
  dtype=bf16  seq=  4096  d= 16  fwd  flash=0.066ms  pt=0.402ms  |  bwd  flash=0.647ms  pt=0.453ms  |  e2e  flash=0.868ms  pt=0.840ms
  dtype=bf16  seq=  4096  d= 32  fwd  flash=0.060ms  pt=0.402ms  |  bwd  flash=0.648ms  pt=0.424ms  |  e2e  flash=0.883ms  pt=0.809ms
  dtype=bf16  seq=  4096  d= 64  fwd  flash=0.094ms  pt=0.409ms  |  bwd  flash=0.899ms  pt=0.437ms  |  e2e  flash=0.988ms  pt=0.835ms
  dtype=bf16  seq=  4096  d=128  fwd  flash=0.144ms  pt=0.428ms  |  bwd  flash=1.545ms  pt=0.469ms  |  e2e  flash=1.685ms  pt=0.885ms
  dtype=bf16  seq=  8192  d= 16  fwd  flash=0.161ms  pt=1.362ms  |  bwd  flash=1.862ms  pt=1.463ms  |  e2e  flash=2.018ms  pt=2.799ms
  dtype=bf16  seq=  8192  d= 32  fwd  flash=0.165ms  pt=1.363ms  |  bwd  flash=2.072ms  pt=1.429ms  |  e2e  flash=2.233ms  pt=2.766ms
  dtype=bf16  seq=  8192  d= 64  fwd  flash=0.255ms  pt=1.399ms  |  bwd  flash=3.365ms  pt=1.468ms  |  e2e  flash=3.617ms  pt=2.849ms
  dtype=bf16  seq=  8192  d=128  fwd  flash=0.549ms  pt=1.445ms  |  bwd  flash=5.665ms  pt=1.546ms  |  e2e  flash=6.212ms  pt=2.970ms
  dtype=bf16  seq= 16384  d= 16  fwd  flash=0.421ms  pt=5.127ms  |  bwd  flash=7.310ms  pt=5.412ms  |  e2e  flash=7.729ms  pt=10.529ms
  dtype=bf16  seq= 16384  d= 32  fwd  flash=0.459ms  pt=5.170ms  |  bwd  flash=8.082ms  pt=5.377ms  |  e2e  flash=8.537ms  pt=10.462ms
  dtype=bf16  seq= 16384  d= 64  fwd  flash=0.685ms  pt=5.259ms  |  bwd  flash=12.864ms  pt=5.491ms  |  e2e  flash=13.562ms  pt=10.695ms
  dtype=bf16  seq= 16384  d=128  fwd  flash=1.620ms  pt=5.436ms  |  bwd  flash=22.182ms  pt=5.699ms  |  e2e  flash=23.791ms  pt=11.098ms
  dtype=bf16  seq= 32768  d= 16  fwd  flash=1.263ms  pt=20.636ms  |  bwd  flash=28.769ms  pt=22.767ms  |  e2e  flash=30.019ms  pt=42.979ms
  dtype=bf16  seq= 32768  d= 32  fwd  flash=1.461ms  pt=20.629ms  |  bwd  flash=31.772ms  pt=22.007ms  |  e2e  flash=33.223ms  pt=42.217ms
  dtype=bf16  seq= 32768  d= 64  fwd  flash=2.256ms  pt=21.067ms  |  bwd  flash=49.687ms  pt=22.523ms  |  e2e  flash=51.910ms  pt=43.191ms
  dtype=bf16  seq= 32768  d=128  fwd  flash=5.362ms  pt=21.733ms  |  bwd  flash=85.629ms  pt=23.336ms  |  e2e  flash=91.015ms  pt=44.678ms
  dtype=bf16  seq= 65536  d= 16  fwd  flash=4.742ms  pt=85.337ms  |  bwd  flash=118.100ms  pt=88.072ms  |  e2e  flash=123.289ms  pt=171.246ms
  dtype=bf16  seq= 65536  d= 32  fwd  flash=5.530ms  pt=85.402ms  |  bwd  flash=129.721ms  pt=88.282ms  |  e2e  flash=135.704ms  pt=171.622ms
  dtype=bf16  seq= 65536  d= 64  fwd  flash=8.756ms  pt=87.017ms  |  bwd  flash=203.142ms  pt=89.884ms  |  e2e  flash=211.779ms  pt=174.625ms
  dtype=bf16  seq= 65536  d=128  fwd  flash=21.365ms  pt=91.605ms  |  bwd  flash=348.764ms  pt=95.319ms  |  e2e  flash=369.537ms  pt=184.561ms
  dtype=fp32  seq=   128  d= 16  fwd  flash=0.025ms  pt=0.109ms  |  bwd  flash=0.526ms  pt=0.255ms  |  e2e  flash=0.757ms  pt=0.582ms
  dtype=fp32  seq=   128  d= 32  fwd  flash=0.026ms  pt=0.101ms  |  bwd  flash=0.509ms  pt=0.245ms  |  e2e  flash=0.757ms  pt=0.560ms
  dtype=fp32  seq=   128  d= 64  fwd  flash=0.028ms  pt=0.108ms  |  bwd  flash=0.508ms  pt=0.240ms  |  e2e  flash=0.757ms  pt=0.581ms
  dtype=fp32  seq=   128  d=128  [Flash OOR(shmem)]  fwd  flash=nanms  pt=0.107ms  |  bwd  flash=nanms  pt=0.233ms  |  e2e  flash=nanms  pt=0.571ms
  dtype=fp32  seq=   256  d= 16  fwd  flash=0.029ms  pt=0.117ms  |  bwd  flash=0.513ms  pt=0.277ms  |  e2e  flash=0.740ms  pt=0.572ms
  dtype=fp32  seq=   256  d= 32  fwd  flash=0.037ms  pt=0.114ms  |  bwd  flash=0.544ms  pt=0.398ms  |  e2e  flash=0.837ms  pt=0.608ms
  dtype=fp32  seq=   256  d= 64  fwd  flash=0.037ms  pt=0.114ms  |  bwd  flash=0.519ms  pt=0.301ms  |  e2e  flash=0.836ms  pt=0.654ms
  dtype=fp32  seq=   256  d=128  [Flash OOR(shmem)]  fwd  flash=nanms  pt=0.118ms  |  bwd  flash=nanms  pt=0.304ms  |  e2e  flash=nanms  pt=0.584ms
  dtype=fp32  seq=   512  d= 16  fwd  flash=0.030ms  pt=0.111ms  |  bwd  flash=0.529ms  pt=0.253ms  |  e2e  flash=0.764ms  pt=0.587ms
  dtype=fp32  seq=   512  d= 32  fwd  flash=0.026ms  pt=0.115ms  |  bwd  flash=0.517ms  pt=0.250ms  |  e2e  flash=0.759ms  pt=0.587ms
  dtype=fp32  seq=   512  d= 64  fwd  flash=0.033ms  pt=0.110ms  |  bwd  flash=0.525ms  pt=0.252ms  |  e2e  flash=0.758ms  pt=0.618ms
  dtype=fp32  seq=   512  d=128  [Flash OOR(shmem)]  fwd  flash=nanms  pt=0.108ms  |  bwd  flash=nanms  pt=0.247ms  |  e2e  flash=nanms  pt=0.579ms
  dtype=fp32  seq=  1024  d= 16  fwd  flash=0.028ms  pt=0.111ms  |  bwd  flash=0.525ms  pt=0.260ms  |  e2e  flash=0.769ms  pt=0.594ms
  dtype=fp32  seq=  1024  d= 32  fwd  flash=0.030ms  pt=0.118ms  |  bwd  flash=0.520ms  pt=0.250ms  |  e2e  flash=0.763ms  pt=0.599ms
  dtype=fp32  seq=  1024  d= 64  fwd  flash=0.054ms  pt=0.118ms  |  bwd  flash=0.530ms  pt=0.253ms  |  e2e  flash=0.781ms  pt=0.589ms
  dtype=fp32  seq=  1024  d=128  [Flash OOR(shmem)]  fwd  flash=nanms  pt=0.111ms  |  bwd  flash=nanms  pt=0.256ms  |  e2e  flash=nanms  pt=0.582ms
  dtype=fp32  seq=  2048  d= 16  fwd  flash=0.037ms  pt=0.178ms  |  bwd  flash=0.530ms  pt=0.252ms  |  e2e  flash=0.786ms  pt=0.594ms
  dtype=fp32  seq=  2048  d= 32  fwd  flash=0.047ms  pt=0.182ms  |  bwd  flash=0.525ms  pt=0.254ms  |  e2e  flash=0.779ms  pt=0.594ms
  dtype=fp32  seq=  2048  d= 64  fwd  flash=0.101ms  pt=0.211ms  |  bwd  flash=0.531ms  pt=0.298ms  |  e2e  flash=0.778ms  pt=0.598ms
  dtype=fp32  seq=  2048  d=128  [Flash OOR(shmem)]  fwd  flash=nanms  pt=0.267ms  |  bwd  flash=nanms  pt=0.461ms  |  e2e  flash=nanms  pt=0.726ms
  dtype=fp32  seq=  4096  d= 16  fwd  flash=0.066ms  pt=0.599ms  |  bwd  flash=0.531ms  pt=0.820ms  |  e2e  flash=0.783ms  pt=1.410ms
  dtype=fp32  seq=  4096  d= 32  fwd  flash=0.085ms  pt=0.623ms  |  bwd  flash=0.578ms  pt=0.844ms  |  e2e  flash=0.777ms  pt=1.460ms
  dtype=fp32  seq=  4096  d= 64  fwd  flash=0.193ms  pt=0.732ms  |  bwd  flash=0.883ms  pt=1.083ms  |  e2e  flash=1.073ms  pt=1.811ms
  dtype=fp32  seq=  4096  d=128  [Flash OOR(shmem)]  fwd  flash=nanms  pt=0.963ms  |  bwd  flash=nanms  pt=1.612ms  |  e2e  flash=nanms  pt=2.575ms
  dtype=fp32  seq=  8192  d= 16  fwd  flash=0.192ms  pt=2.135ms  |  bwd  flash=1.845ms  pt=3.076ms  |  e2e  flash=2.031ms  pt=5.198ms
  dtype=fp32  seq=  8192  d= 32  fwd  flash=0.261ms  pt=2.241ms  |  bwd  flash=2.054ms  pt=3.054ms  |  e2e  flash=2.310ms  pt=5.289ms
  dtype=fp32  seq=  8192  d= 64  fwd  flash=0.744ms  pt=2.685ms  |  bwd  flash=3.345ms  pt=4.183ms  |  e2e  flash=4.087ms  pt=6.869ms
  dtype=fp32  seq=  8192  d=128  [Flash OOR(shmem)]  fwd  flash=nanms  pt=3.628ms  |  bwd  flash=nanms  pt=5.974ms  |  e2e  flash=nanms  pt=9.602ms
  dtype=fp32  seq= 16384  d= 16  fwd  flash=0.531ms  pt=8.399ms  |  bwd  flash=7.266ms  pt=12.005ms  |  e2e  flash=7.789ms  pt=20.372ms
  dtype=fp32  seq= 16384  d= 32  fwd  flash=0.806ms  pt=8.774ms  |  bwd  flash=8.017ms  pt=12.591ms  |  e2e  flash=8.817ms  pt=21.341ms
  dtype=fp32  seq= 16384  d= 64  fwd  flash=2.210ms  pt=10.804ms  |  bwd  flash=12.791ms  pt=16.429ms  |  e2e  flash=14.991ms  pt=27.254ms
  dtype=fp32  seq= 16384  d=128  [Flash OOR(shmem)]  fwd  flash=nanms  pt=14.569ms  |  bwd  flash=nanms  pt=23.924ms  |  e2e  flash=nanms  pt=38.444ms
  dtype=fp32  seq= 32768  d= 16  fwd  flash=1.703ms  pt=37.881ms  |  bwd  flash=28.859ms  pt=47.913ms  |  e2e  flash=30.337ms  pt=84.940ms
  dtype=fp32  seq= 32768  d= 32  fwd  flash=2.570ms  pt=39.129ms  |  bwd  flash=32.310ms  pt=49.876ms  |  e2e  flash=34.410ms  pt=88.370ms
  dtype=fp32  seq= 32768  d= 64  fwd  flash=7.328ms  pt=45.578ms  |  bwd  flash=49.580ms  pt=64.167ms  |  e2e  flash=56.832ms  pt=109.904ms
  dtype=fp32  seq= 32768  d=128  [Flash OOR(shmem)]  fwd  flash=nanms  pt=60.677ms  |  bwd  flash=nanms  pt=92.726ms  |  e2e  flash=nanms  pt=152.519ms
  dtype=fp32  seq= 65536  d= 16  [PyTorch OOM]  fwd  flash=6.495ms  pt=nanms  |  bwd  flash=118.748ms  pt=nanms  |  e2e  flash=125.561ms  pt=nanms
  dtype=fp32  seq= 65536  d= 32  [PyTorch OOM]  fwd  flash=9.995ms  pt=nanms  |  bwd  flash=132.674ms  pt=nanms  |  e2e  flash=141.911ms  pt=nanms
  dtype=fp32  seq= 65536  d= 64  [PyTorch OOM]  fwd  flash=29.237ms  pt=nanms  |  bwd  flash=202.949ms  pt=nanms  |  e2e  flash=232.531ms  pt=nanms
  dtype=fp32  seq= 65536  d=128  [Flash OOR(shmem)]  [PyTorch OOM]  fwd  flash=nanms  pt=nanms  |  bwd  flash=nanms  pt=nanms  |  e2e  flash=nanms  pt=nanms

=== dtype=bf16  d=16 ===
         fwd_flash_ms  fwd_pt_ms  fwd_speedup  bwd_flash_ms  bwd_pt_ms  bwd_speedup  e2e_flash_ms  e2e_pt_ms  e2e_speedup
seq_len
128            0.0256     0.1073         4.19        0.4896     0.2454         0.50        0.7341     0.5667         0.77
256            0.0414     0.1157         2.80        0.6045     0.2606         0.43        0.8554     0.5953         0.70
512            0.0416     0.1152         2.77        0.6073     0.2432         0.40        0.8522     0.5813         0.68
1024           0.0268     0.1154         4.31        0.7329     0.3997         0.55        0.9526     0.6926         0.73
2048           0.0380     0.1309         3.45        0.6238     0.2462         0.39        0.8614     0.5910         0.69
4096           0.0659     0.4020         6.10        0.6472     0.4532         0.70        0.8678     0.8401         0.97
8192           0.1612     1.3621         8.45        1.8619     1.4633         0.79        2.0175     2.7994         1.39
16384          0.4208     5.1269        12.18        7.3105     5.4120         0.74        7.7286    10.5293         1.36
32768          1.2631    20.6364        16.34       28.7689    22.7668         0.79       30.0192    42.9788         1.43
65536          4.7420    85.3371        18.00      118.1000    88.0722         0.75      123.2886   171.2456         1.39

=== dtype=bf16  d=32 ===
         fwd_flash_ms  fwd_pt_ms  fwd_speedup  bwd_flash_ms  bwd_pt_ms  bwd_speedup  e2e_flash_ms  e2e_pt_ms  e2e_speedup
seq_len
128            0.0232     0.1051         4.53        0.5681     0.3168         0.56        0.8163     0.6073         0.74
256            0.0277     0.1094         3.96        0.6146     0.3826         0.62        0.8644     0.6651         0.77
512            0.0323     0.1333         4.13        0.6227     0.2457         0.39        0.8591     0.5879         0.68
1024           0.0285     0.1170         4.11        0.7372     0.2746         0.37        0.9524     0.5954         0.63
2048           0.0393     0.1311         3.33        0.6216     0.2349         0.38        0.8662     0.5495         0.63
4096           0.0604     0.4018         6.66        0.6478     0.4245         0.66        0.8833     0.8088         0.92
8192           0.1646     1.3634         8.28        2.0715     1.4293         0.69        2.2325     2.7663         1.24
16384          0.4588     5.1702        11.27        8.0824     5.3771         0.67        8.5372    10.4624         1.23
32768          1.4615    20.6287        14.11       31.7716    22.0065         0.69       33.2227    42.2175         1.27
65536          5.5301    85.4016        15.44      129.7213    88.2821         0.68      135.7036   171.6224         1.26

=== dtype=bf16  d=64 ===
         fwd_flash_ms  fwd_pt_ms  fwd_speedup  bwd_flash_ms  bwd_pt_ms  bwd_speedup  e2e_flash_ms  e2e_pt_ms  e2e_speedup
seq_len
128            0.0368     0.1170         3.18        0.5716     0.2364         0.41        0.8420     0.5763         0.68
256            0.0236     0.1152         4.89        0.7068     0.2604         0.37        0.9086     0.6040         0.66
512            0.0293     0.1186         4.05        0.6168     0.2551         0.41        0.8643     0.5954         0.69
1024           0.0302     0.1108         3.67        0.6286     0.2762         0.44        0.8820     0.5850         0.66
2048           0.0505     0.1337         2.65        0.6031     0.2425         0.40        0.8652     0.5818         0.67
4096           0.0939     0.4095         4.36        0.8985     0.4367         0.49        0.9881     0.8350         0.85
8192           0.2547     1.3990         5.49        3.3653     1.4683         0.44        3.6167     2.8493         0.79
16384          0.6851     5.2592         7.68       12.8636     5.4907         0.43       13.5619    10.6950         0.79
32768          2.2564    21.0670         9.34       49.6865    22.5231         0.45       51.9096    43.1913         0.83
65536          8.7559    87.0175         9.94      203.1422    89.8837         0.44      211.7786   174.6248         0.82

=== dtype=bf16  d=128 ===
         fwd_flash_ms  fwd_pt_ms  fwd_speedup  bwd_flash_ms  bwd_pt_ms  bwd_speedup  e2e_flash_ms  e2e_pt_ms  e2e_speedup
seq_len
128            0.0278     0.1123         4.04        0.5545     0.2430         0.44        0.7970     0.6000         0.75
256            0.0284     0.1159         4.08        0.6269     0.2578         0.41        0.8640     0.6208         0.72
512            0.0410     0.1032         2.51        0.6833     0.3930         0.58        0.9278     0.6757         0.73
1024           0.0456     0.1080         2.37        0.6212     0.2401         0.39        0.8488     0.5844         0.69
2048           0.0766     0.1399         1.83        0.6402     0.2536         0.40        0.8788     0.6074         0.69
4096           0.1443     0.4277         2.96        1.5452     0.4687         0.30        1.6852     0.8848         0.53
8192           0.5488     1.4448         2.63        5.6649     1.5461         0.27        6.2116     2.9700         0.48
16384          1.6197     5.4357         3.36       22.1816     5.6992         0.26       23.7914    11.0976         0.47
32768          5.3618    21.7326         4.05       85.6289    23.3362         0.27       91.0152    44.6781         0.49
65536         21.3652    91.6050         4.29      348.7642    95.3190         0.27      369.5370   184.5606         0.50

=== dtype=fp32  d=16 ===
         fwd_flash_ms  fwd_pt_ms  fwd_speedup  bwd_flash_ms  bwd_pt_ms  bwd_speedup  e2e_flash_ms  e2e_pt_ms  e2e_speedup
seq_len
128            0.0247     0.1089         4.41        0.5264     0.2550         0.48        0.7570     0.5818         0.77
256            0.0293     0.1166         3.98        0.5127     0.2774         0.54        0.7403     0.5721         0.77
512            0.0303     0.1109         3.66        0.5289     0.2533         0.48        0.7636     0.5869         0.77
1024           0.0279     0.1111         3.98        0.5250     0.2604         0.50        0.7694     0.5938         0.77
2048           0.0369     0.1780         4.82        0.5303     0.2516         0.47        0.7864     0.5939         0.76
4096           0.0659     0.5986         9.08        0.5315     0.8195         1.54        0.7829     1.4100         1.80
8192           0.1920     2.1348        11.12        1.8453     3.0765         1.67        2.0314     5.1980         2.56
16384          0.5305     8.3988        15.83        7.2656    12.0049         1.65        7.7894    20.3717         2.62
32768          1.7034    37.8813        22.24       28.8594    47.9135         1.66       30.3370    84.9398         2.80
65536          6.4952        NaN          NaN      118.7482        NaN          NaN      125.5608        NaN          NaN

=== dtype=fp32  d=32 ===
         fwd_flash_ms  fwd_pt_ms  fwd_speedup  bwd_flash_ms  bwd_pt_ms  bwd_speedup  e2e_flash_ms  e2e_pt_ms  e2e_speedup
seq_len
128            0.0255     0.1009         3.95        0.5093     0.2455         0.48        0.7567     0.5598         0.74
256            0.0370     0.1140         3.09        0.5443     0.3978         0.73        0.8371     0.6079         0.73
512            0.0263     0.1153         4.39        0.5169     0.2501         0.48        0.7591     0.5866         0.77
1024           0.0299     0.1179         3.94        0.5196     0.2503         0.48        0.7628     0.5986         0.78
2048           0.0469     0.1822         3.89        0.5252     0.2539         0.48        0.7791     0.5940         0.76
4096           0.0851     0.6232         7.32        0.5781     0.8441         1.46        0.7771     1.4601         1.88
8192           0.2614     2.2407         8.57        2.0538     3.0543         1.49        2.3101     5.2893         2.29
16384          0.8061     8.7738        10.88        8.0174    12.5912         1.57        8.8166    21.3409         2.42
32768          2.5701    39.1291        15.22       32.3096    49.8760         1.54       34.4105    88.3702         2.57
65536          9.9952        NaN          NaN      132.6735        NaN          NaN      141.9110        NaN          NaN

=== dtype=fp32  d=64 ===
         fwd_flash_ms  fwd_pt_ms  fwd_speedup  bwd_flash_ms  bwd_pt_ms  bwd_speedup  e2e_flash_ms  e2e_pt_ms  e2e_speedup
seq_len

### Sanity Check Reruns

In [14]:
import subprocess

cmd = """
uv run python ./student/flash_attention_benchmarking.py
"""

output = subprocess.check_output(
    cmd,
    shell=True,
    text=True,
    stderr=subprocess.STDOUT
)

print(output)

Using CPython 3.12.12 interpreter at: /usr/bin/python3
Creating virtual environment at: .venv
Installed 75 packages in 234ms
GPU: NVIDIA A100-SXM4-80GB
PyTorch: 2.6.0+cu124
Triton:  3.2.0

Running benchmark sweep...
  dtype=bf16  seq=   128  d= 16  /content/llmr-a2/.venv/lib/python3.12/site-packages/torch/_inductor/compile_fx.py:194: UserWarning: TensorFloat32 tensor cores for float32 matrix multiplication available but not enabled. Consider setting `torch.set_float32_matmul_precision('high')` for better performance.
  warnings.warn(
fwd  flash=0.038ms  pt=0.118ms  |  bwd  flash=0.481ms  pt=0.261ms  |  e2e  flash=0.747ms  pt=0.590ms
  dtype=bf16  seq=   128  d= 32  fwd  flash=0.040ms  pt=0.118ms  |  bwd  flash=0.580ms  pt=0.246ms  |  e2e  flash=0.842ms  pt=0.581ms
  dtype=bf16  seq=   128  d= 64  fwd  flash=0.191ms  pt=0.118ms  |  bwd  flash=0.575ms  pt=0.243ms  |  e2e  flash=0.843ms  pt=0.595ms
  dtype=bf16  seq=   128  d=128  fwd  flash=1.101ms  pt=0.129ms  |  bwd  flash=0.565ms  pt=0.251ms  |  e2e  flash=0.987ms  pt=0.602ms
  dtype=bf16  seq=   256  d= 16  fwd  flash=0.040ms  pt=0.123ms  |  bwd  flash=0.625ms  pt=0.261ms  |  e2e  flash=0.872ms  pt=0.601ms
  dtype=bf16  seq=   256  d= 32  fwd  flash=0.070ms  pt=0.121ms  |  bwd  flash=0.604ms  pt=0.252ms  |  e2e  flash=0.857ms  pt=0.603ms
  dtype=bf16  seq=   256  d= 64  fwd  flash=0.848ms  pt=0.130ms  |  bwd  flash=0.630ms  pt=0.302ms  |  e2e  flash=0.898ms  pt=0.737ms
  dtype=bf16  seq=   256  d=128  fwd  flash=2.089ms  pt=0.124ms  |  bwd  flash=0.761ms  pt=0.414ms  |  e2e  flash=1.894ms  pt=0.724ms
  dtype=bf16  seq=   512  d= 16  fwd  flash=0.050ms  pt=0.128ms  |  bwd  flash=0.751ms  pt=0.410ms  |  e2e  flash=0.992ms  pt=0.725ms
  dtype=bf16  seq=   512  d= 32  fwd  flash=0.131ms  pt=0.129ms  |  bwd  flash=0.746ms  pt=0.261ms  |  e2e  flash=0.990ms  pt=0.613ms
  dtype=bf16  seq=   512  d= 64  fwd  flash=1.791ms  pt=0.128ms  |  bwd  flash=0.641ms  pt=0.260ms  |  e2e  flash=1.563ms  pt=0.608ms
  dtype=bf16  seq=   512  d=128  fwd  flash=4.480ms  pt=0.118ms  |  bwd  flash=0.625ms  pt=0.260ms  |  e2e  flash=3.782ms  pt=0.588ms
  dtype=bf16  seq=  1024  d= 16  fwd  flash=0.093ms  pt=0.128ms  |  bwd  flash=0.625ms  pt=0.254ms  |  e2e  flash=0.890ms  pt=0.613ms
  dtype=bf16  seq=  1024  d= 32  fwd  flash=0.257ms  pt=0.127ms  |  bwd  flash=0.633ms  pt=0.276ms  |  e2e  flash=0.914ms  pt=0.638ms
  dtype=bf16  seq=  1024  d= 64  fwd  flash=3.662ms  pt=0.132ms  |  bwd  flash=0.651ms  pt=0.274ms  |  e2e  flash=3.132ms  pt=0.591ms
  dtype=bf16  seq=  1024  d=128  fwd  flash=8.710ms  pt=0.115ms  |  bwd  flash=0.649ms  pt=0.249ms  |  e2e  flash=7.879ms  pt=0.595ms
  dtype=bf16  seq=  2048  d= 16  fwd  flash=0.177ms  pt=0.132ms  |  bwd  flash=0.642ms  pt=0.264ms  |  e2e  flash=0.924ms  pt=0.621ms
  dtype=bf16  seq=  2048  d= 32  fwd  flash=0.508ms  pt=0.138ms  |  bwd  flash=0.646ms  pt=0.305ms  |  e2e  flash=0.908ms  pt=0.649ms
  dtype=bf16  seq=  2048  d= 64  fwd  flash=7.918ms  pt=0.134ms  |  bwd  flash=0.630ms  pt=0.243ms  |  e2e  flash=6.855ms  pt=0.581ms
  dtype=bf16  seq=  2048  d=128  fwd  flash=18.739ms  pt=0.139ms  |  bwd  flash=0.718ms  pt=0.256ms  |  e2e  flash=19.242ms  pt=0.631ms
  dtype=bf16  seq=  4096  d= 16  fwd  flash=0.347ms  pt=0.402ms  |  bwd  flash=0.661ms  pt=0.452ms  |  e2e  flash=0.918ms  pt=0.839ms
  dtype=bf16  seq=  4096  d= 32  fwd  flash=1.021ms  pt=0.402ms  |  bwd  flash=0.668ms  pt=0.423ms  |  e2e  flash=1.421ms  pt=0.807ms
  dtype=bf16  seq=  4096  d= 64  fwd  flash=19.539ms  pt=0.410ms  |  bwd  flash=0.898ms  pt=0.436ms  |  e2e  flash=20.438ms  pt=0.833ms
  dtype=bf16  seq=  4096  d=128  fwd  flash=65.120ms  pt=0.428ms  |  bwd  flash=1.548ms  pt=0.468ms  |  e2e  flash=66.641ms  pt=0.884ms
  dtype=bf16  seq=  8192  d= 16  fwd  flash=1.126ms  pt=1.358ms  |  bwd  flash=1.855ms  pt=1.465ms  |  e2e  flash=2.987ms  pt=2.791ms
  dtype=bf16  seq=  8192  d= 32  fwd  flash=3.505ms  pt=1.359ms  |  bwd  flash=2.116ms  pt=1.431ms  |  e2e  flash=4.992ms  pt=2.762ms
  dtype=bf16  seq=  8192  d= 64  fwd  flash=65.777ms  pt=1.398ms  |  bwd  flash=3.365ms  pt=1.469ms  |  e2e  flash=69.136ms  pt=2.842ms
  dtype=bf16  seq=  8192  d=128  fwd  flash=210.826ms  pt=1.444ms  |  bwd  flash=5.672ms  pt=1.545ms  |  e2e  flash=217.491ms  pt=2.966ms
  dtype=bf16  seq= 16384  d= 16  fwd  flash=3.465ms  pt=5.131ms  |  bwd  flash=7.292ms  pt=5.398ms  |  e2e  flash=10.757ms  pt=10.495ms
  dtype=bf16  seq= 16384  d= 32  fwd  flash=13.831ms  pt=5.168ms  |  bwd  flash=8.061ms  pt=5.356ms  |  e2e  flash=21.212ms  pt=10.442ms
  dtype=bf16  seq= 16384  d= 64  fwd  flash=225.554ms  pt=5.285ms  |  bwd  flash=12.844ms  pt=5.478ms  |  e2e  flash=236.705ms  pt=10.694ms
  dtype=bf16  seq= 16384  d=128  fwd  flash=784.995ms  pt=5.438ms  |  bwd  flash=22.221ms  pt=5.681ms  |  e2e  flash=810.538ms  pt=11.089ms
  dtype=bf16  seq= 32768  d= 16  fwd  flash=11.235ms  pt=20.635ms  |  bwd  flash=28.773ms  pt=22.762ms  |  e2e  flash=39.905ms  pt=42.954ms
  dtype=bf16  seq= 32768  d= 32  fwd  flash=45.150ms  pt=20.653ms  |  bwd  flash=31.804ms  pt=21.970ms  |  e2e  flash=77.096ms  pt=42.235ms
  dtype=bf16  seq= 32768  d= 64  fwd  flash=867.824ms  pt=21.098ms  |  bwd  flash=49.594ms  pt=22.521ms  |  e2e  flash=918.703ms  pt=43.109ms
  dtype=bf16  seq= 32768  d=128  fwd  flash=2990.088ms  pt=21.769ms  |  bwd  flash=85.618ms  pt=23.317ms  |  e2e  flash=3070.125ms  pt=44.711ms
  dtype=bf16  seq= 65536  d= 16  fwd  flash=43.884ms  pt=85.358ms  |  bwd  flash=117.427ms  pt=88.051ms  |  e2e  flash=160.944ms  pt=171.142ms
  dtype=bf16  seq= 65536  d= 32  fwd  flash=172.157ms  pt=85.391ms  |  bwd  flash=130.249ms  pt=88.152ms  |  e2e  flash=302.585ms  pt=171.321ms
  dtype=bf16  seq= 65536  d= 64  fwd  flash=3171.408ms  pt=87.028ms  |  bwd  flash=202.461ms  pt=89.744ms  |  e2e  flash=3372.986ms  pt=174.655ms
  dtype=bf16  seq= 65536  d=128  fwd  flash=11769.982ms  pt=91.576ms  |  bwd  flash=347.990ms  pt=94.948ms  |  e2e  flash=12124.144ms  pt=184.723ms
  dtype=fp32  seq=   128  d= 16  fwd  flash=0.032ms  pt=0.120ms  |  bwd  flash=0.528ms  pt=0.255ms  |  e2e  flash=0.790ms  pt=0.593ms
  dtype=fp32  seq=   128  d= 32  fwd  flash=0.044ms  pt=0.114ms  |  bwd  flash=0.528ms  pt=0.255ms  |  e2e  flash=0.783ms  pt=0.583ms
  dtype=fp32  seq=   128  d= 64  fwd  flash=0.077ms  pt=0.124ms  |  bwd  flash=0.523ms  pt=0.253ms  |  e2e  flash=0.790ms  pt=0.590ms
  dtype=fp32  seq=   128  d=128  [Flash OOR(shmem)]  fwd  flash=nanms  pt=0.121ms  |  bwd  flash=nanms  pt=0.240ms  |  e2e  flash=nanms  pt=0.574ms
  dtype=fp32  seq=   256  d= 16  fwd  flash=0.041ms  pt=0.117ms  |  bwd  flash=0.528ms  pt=0.259ms  |  e2e  flash=0.832ms  pt=0.608ms
  dtype=fp32  seq=   256  d= 32  fwd  flash=0.046ms  pt=0.123ms  |  bwd  flash=0.524ms  pt=0.256ms  |  e2e  flash=0.784ms  pt=0.605ms
  dtype=fp32  seq=   256  d= 64  fwd  flash=1.063ms  pt=0.122ms  |  bwd  flash=0.549ms  pt=0.259ms  |  e2e  flash=0.951ms  pt=0.601ms
  dtype=fp32  seq=   256  d=128  [Flash OOR(shmem)]  fwd  flash=nanms  pt=0.121ms  |  bwd  flash=nanms  pt=0.270ms  |  e2e  flash=nanms  pt=0.603ms
  dtype=fp32  seq=   512  d= 16  fwd  flash=0.043ms  pt=0.119ms  |  bwd  flash=0.543ms  pt=0.253ms  |  e2e  flash=0.772ms  pt=0.593ms
  dtype=fp32  seq=   512  d= 32  fwd  flash=0.069ms  pt=0.154ms  |  bwd  flash=0.542ms  pt=0.310ms  |  e2e  flash=0.795ms  pt=0.639ms
  dtype=fp32  seq=   512  d= 64  fwd  flash=2.050ms  pt=0.123ms  |  bwd  flash=0.534ms  pt=0.261ms  |  e2e  flash=1.882ms  pt=0.607ms
  dtype=fp32  seq=   512  d=128  [Flash OOR(shmem)]  fwd  flash=nanms  pt=0.120ms  |  bwd  flash=nanms  pt=0.252ms  |  e2e  flash=nanms  pt=0.634ms
  dtype=fp32  seq=  1024  d= 16  fwd  flash=0.080ms  pt=0.126ms  |  bwd  flash=0.567ms  pt=0.269ms  |  e2e  flash=0.839ms  pt=0.615ms
  dtype=fp32  seq=  1024  d= 32  fwd  flash=0.124ms  pt=0.136ms  |  bwd  flash=0.560ms  pt=0.264ms  |  e2e  flash=0.802ms  pt=0.638ms
  dtype=fp32  seq=  1024  d= 64  fwd  flash=4.518ms  pt=0.131ms  |  bwd  flash=0.565ms  pt=0.265ms  |  e2e  flash=3.820ms  pt=0.624ms
  dtype=fp32  seq=  1024  d=128  [Flash OOR(shmem)]  fwd  flash=nanms  pt=0.130ms  |  bwd  flash=nanms  pt=0.271ms  |  e2e  flash=nanms  pt=0.623ms
  dtype=fp32  seq=  2048  d= 16  fwd  flash=0.131ms  pt=0.178ms  |  bwd  flash=0.565ms  pt=0.270ms  |  e2e  flash=0.832ms  pt=0.632ms
  dtype=fp32  seq=  2048  d= 32  fwd  flash=0.247ms  pt=0.182ms  |  bwd  flash=0.545ms  pt=0.271ms  |  e2e  flash=0.804ms  pt=0.624ms
  dtype=fp32  seq=  2048  d= 64  fwd  flash=8.479ms  pt=0.211ms  |  bwd  flash=0.548ms  pt=0.300ms  |  e2e  flash=7.902ms  pt=0.678ms
  dtype=fp32  seq=  2048  d=128  [Flash OOR(shmem)]  fwd  flash=nanms  pt=0.318ms  |  bwd  flash=nanms  pt=0.460ms  |  e2e  flash=nanms  pt=0.726ms
  dtype=fp32  seq=  4096  d= 16  fwd  flash=0.253ms  pt=0.598ms  |  bwd  flash=0.576ms  pt=0.818ms  |  e2e  flash=0.860ms  pt=1.409ms
  dtype=fp32  seq=  4096  d= 32  fwd  flash=0.476ms  pt=0.623ms  |  bwd  flash=0.579ms  pt=0.845ms  |  e2e  flash=1.044ms  pt=1.460ms
  dtype=fp32  seq=  4096  d= 64  fwd  flash=17.185ms  pt=0.733ms  |  bwd  flash=0.886ms  pt=1.083ms  |  e2e  flash=18.062ms  pt=1.812ms
  dtype=fp32  seq=  4096  d=128  [Flash OOR(shmem)]  fwd  flash=nanms  pt=1.113ms  |  bwd  flash=nanms  pt=1.847ms  |  e2e  flash=nanms  pt=2.576ms
  dtype=fp32  seq=  8192  d= 16  fwd  flash=0.910ms  pt=2.132ms  |  bwd  flash=1.844ms  pt=3.084ms  |  e2e  flash=2.757ms  pt=5.194ms
  dtype=fp32  seq=  8192  d= 32  fwd  flash=1.538ms  pt=2.237ms  |  bwd  flash=2.054ms  pt=3.064ms  |  e2e  flash=3.593ms  pt=5.283ms
  dtype=fp32  seq=  8192  d= 64  fwd  flash=74.903ms  pt=2.684ms  |  bwd  flash=3.345ms  pt=4.190ms  |  e2e  flash=77.998ms  pt=6.863ms
  dtype=fp32  seq=  8192  d=128  [Flash OOR(shmem)]  fwd  flash=nanms  pt=4.126ms  |  bwd  flash=nanms  pt=6.546ms  |  e2e  flash=nanms  pt=9.607ms
  dtype=fp32  seq= 16384  d= 16  fwd  flash=2.666ms  pt=8.415ms  |  bwd  flash=7.278ms  pt=12.013ms  |  e2e  flash=9.950ms  pt=20.387ms
  dtype=fp32  seq= 16384  d= 32  fwd  flash=4.550ms  pt=8.786ms  |  bwd  flash=8.049ms  pt=12.605ms  |  e2e  flash=12.593ms  pt=21.358ms
  dtype=fp32  seq= 16384  d= 64  fwd  flash=262.441ms  pt=10.824ms  |  bwd  flash=12.821ms  pt=16.447ms  |  e2e  flash=276.196ms  pt=27.264ms
  dtype=fp32  seq= 16384  d=128  [Flash OOR(shmem)]  fwd  flash=nanms  pt=16.623ms  |  bwd  flash=nanms  pt=23.956ms  |  e2e  flash=nanms  pt=38.466ms
  dtype=fp32  seq= 32768  d= 16  fwd  flash=8.795ms  pt=37.823ms  |  bwd  flash=28.740ms  pt=48.020ms  |  e2e  flash=37.451ms  pt=85.057ms
  dtype=fp32  seq= 32768  d= 32  fwd  flash=15.051ms  pt=39.162ms  |  bwd  flash=31.840ms  pt=49.908ms  |  e2e  flash=46.691ms  pt=88.439ms
  dtype=fp32  seq= 32768  d= 64  fwd  flash=991.459ms  pt=45.689ms  |  bwd  flash=49.560ms  pt=64.264ms  |  e2e  flash=1042.829ms  pt=109.790ms
  dtype=fp32  seq= 32768  d=128  [Flash OOR(shmem)]  fwd  flash=nanms  pt=59.911ms  |  bwd  flash=nanms  pt=92.851ms  |  e2e  flash=nanms  pt=152.700ms
  dtype=fp32  seq= 65536  d= 16  [PyTorch OOM]  fwd  flash=34.745ms  pt=nanms  |  bwd  flash=118.800ms  pt=nanms  |  e2e  flash=152.697ms  pt=nanms
  dtype=fp32  seq= 65536  d= 32  [PyTorch OOM]  fwd  flash=59.251ms  pt=nanms  |  bwd  flash=131.124ms  pt=nanms  |  e2e  flash=189.824ms  pt=nanms
  dtype=fp32  seq= 65536  d= 64  [PyTorch OOM]  fwd  flash=3914.450ms  pt=nanms  |  bwd  flash=203.314ms  pt=nanms  |  e2e  flash=4117.050ms  pt=nanms
  dtype=fp32  seq= 65536  d=128  [Flash OOR(shmem)]  [PyTorch OOM]  fwd  flash=nanms  pt=nanms  |  bwd  flash=nanms  pt=nanms  |  e2e  flash=nanms  pt=nanms

=== dtype=bf16  d=16 ===
         fwd_flash_ms  fwd_pt_ms  fwd_speedup  bwd_flash_ms  bwd_pt_ms  bwd_speedup  e2e_flash_ms  e2e_pt_ms  e2e_speedup
seq_len
128            0.0380     0.1175         3.10        0.4814     0.2610         0.54        0.7473     0.5904         0.79
256            0.0404     0.1225         3.04        0.6247     0.2608         0.42        0.8722     0.6011         0.69
512            0.0499     0.1277         2.56        0.7508     0.4097         0.55        0.9922     0.7252         0.73
1024           0.0925     0.1275         1.38        0.6254     0.2538         0.41        0.8902     0.6126         0.69
2048           0.1774     0.1322         0.75        0.6416     0.2640         0.41        0.9240     0.6213         0.67
4096           0.3472     0.4017         1.16        0.6611     0.4520         0.68        0.9178     0.8392         0.91
8192           1.1263     1.3579         1.21        1.8553     1.4649         0.79        2.9872     2.7915         0.93
16384          3.4648     5.1312         1.48        7.2920     5.3984         0.74       10.7575    10.4945         0.98
32768         11.2349    20.6354         1.84       28.7734    22.7617         0.79       39.9053    42.9542         1.08
65536         43.8835    85.3576         1.95      117.4272    88.0507         0.75      160.9441   171.1422         1.06

=== dtype=bf16  d=32 ===
         fwd_flash_ms  fwd_pt_ms  fwd_speedup  bwd_flash_ms  bwd_pt_ms  bwd_speedup  e2e_flash_ms  e2e_pt_ms  e2e_speedup
seq_len
128            0.0402     0.1178         2.93        0.5802     0.2458         0.42        0.8416     0.5812         0.69
256            0.0697     0.1209         1.73        0.6039     0.2520         0.42        0.8565     0.6029         0.70
512            0.1307     0.1289         0.99        0.7464     0.2609         0.35        0.9901     0.6132         0.62
1024           0.2572     0.1267         0.49        0.6332     0.2760         0.44        0.9138     0.6377         0.70
2048           0.5083     0.1376         0.27        0.6457     0.3054         0.47        0.9076     0.6492         0.72
4096           1.0208     0.4016         0.39        0.6680     0.4230         0.63        1.4208     0.8073         0.57
8192           3.5054     1.3586         0.39        2.1158     1.4315         0.68        4.9921     2.7617         0.55
16384         13.8313     5.1679         0.37        8.0608     5.3563         0.66       21.2116    10.4420         0.49
32768         45.1497    20.6525         0.46       31.8041    21.9697         0.69       77.0959    42.2354         0.55
65536        172.1569    85.3914         0.50      130.2487    88.1521         0.68      302.5848   171.3214         0.57

=== dtype=bf16  d=64 ===
         fwd_flash_ms  fwd_pt_ms  fwd_speedup  bwd_flash_ms  bwd_pt_ms  bwd_speedup  e2e_flash_ms  e2e_pt_ms  e2e_speedup
seq_len
128            0.1912     0.1181         0.62        0.5755     0.2430         0.42        0.8429     0.5948         0.71
256            0.8479     0.1300         0.15        0.6297     0.3016         0.48        0.8981     0.7368         0.82
512            1.7910     0.1279         0.07        0.6414     0.2595         0.40        1.5627     0.6080         0.39
1024           3.6616     0.1319         0.04        0.6513     0.2737         0.42        3.1325     0.5908         0.19
2048           7.9177     0.1337         0.02        0.6301     0.2431         0.39        6.8549     0.5812         0.08
4096          19.5392     0.4096         0.02        0.8984     0.4363         0.49       20.4383     0.8330         0.04
8192          65.7766     1.3981         0.02        3.3653     1.4693         0.44       69.1364     2.8424         0.04
16384        225.5544     5.2849         0.02       12.8442     5.4780         0.43      236.7048    10.6940         0.05
32768        867.8236    21.0985         0.02       49.5944    22.5213         0.45      918.7031    43.1094         0.05
65536       3171.4080    87.0277         0.03      202.4612    89.7444         0.44     3372.9863   174.6555         0.05

=== dtype=bf16  d=128 ===
         fwd_flash_ms  fwd_pt_ms  fwd_speedup  bwd_flash_ms  bwd_pt_ms  bwd_speedup  e2e_flash_ms  e2e_pt_ms  e2e_speedup
seq_len
128            1.1014     0.1287         0.12        0.5653     0.2509         0.44        0.9870     0.6019         0.61
256            2.0893     0.1236         0.06        0.7613     0.4136         0.54        1.8942     0.7245         0.38
512            4.4799     0.1176         0.03        0.6253     0.2596         0.42        3.7820     0.5878         0.16
1024           8.7096     0.1153         0.01        0.6485     0.2486         0.38        7.8788     0.5951         0.08
2048          18.7395     0.1394         0.01        0.7178     0.2561         0.36       19.2420     0.6315         0.03
4096          65.1203     0.4277         0.01        1.5482     0.4679         0.30       66.6409     0.8839         0.01
8192         210.8262     1.4444         0.01        5.6717     1.5448         0.27      217.4915     2.9662         0.01
16384        784.9953     5.4379         0.01       22.2211     5.6811         0.26      810.5380    11.0886         0.01
32768       2990.0881    21.7687         0.01       85.6177    23.3167         0.27     3070.1250    44.7114         0.01
65536      11769.9824    91.5763         0.01      347.9900    94.9483         0.27    12124.1436   184.7234         0.02

=== dtype=fp32  d=16 ===
         fwd_flash_ms  fwd_pt_ms  fwd_speedup  bwd_flash_ms  bwd_pt_ms  bwd_speedup  e2e_flash_ms  e2e_pt_ms  e2e_speedup
seq_len
128            0.0316     0.1204         3.81        0.5285     0.2548         0.48        0.7897     0.5925         0.75
256            0.0408     0.1175         2.88        0.5279     0.2591         0.49        0.8319     0.6077         0.73
512            0.0432     0.1193         2.77        0.5433     0.2525         0.46        0.7723     0.5935         0.77
1024           0.0798     0.1261         1.58        0.5665     0.2686         0.47        0.8392     0.6149         0.73
2048           0.1307     0.1780         1.36        0.5655     0.2700         0.48        0.8324     0.6323         0.76
4096           0.2526     0.5982         2.37        0.5763     0.8175         1.42        0.8599     1.4086         1.64
8192           0.9102     2.1321         2.34        1.8441     3.0840         1.67        2.7569     5.1937         1.88
16384          2.6665     8.4146         3.16        7.2780    12.0129         1.65        9.9496    20.3873         2.05
32768          8.7950    37.8235         4.30       28.7396    48.0200         1.67       37.4513    85.0565         2.27
65536         34.7453        NaN          NaN      118.8004        NaN          NaN      152.6968        NaN          NaN

=== dtype=fp32  d=32 ===
         fwd_flash_ms  fwd_pt_ms  fwd_speedup  bwd_flash_ms  bwd_pt_ms  bwd_speedup  e2e_flash_ms  e2e_pt_ms  e2e_speedup
seq_len
128            0.0441     0.1142         2.59        0.5275     0.2548         0.48        0.7827     0.5833         0.75
256            0.0460     0.1232         2.68        0.5241     0.2562         0.49        0.7839     0.6051         0.77
512            0.0689     0.1538         2.23        0.5425     0.3099         0.57        0.7953     0.6392         0.80
1024           0.1236     0.1360         1.10        0.5598     0.2640         0.47        0.8022     0.6382         0.80
2048           0.2466     0.1819         0.74        0.5454     0.2705         0.50        0.8038     0.6242         0.78
4096           0.4758     0.6233         1.31        0.5786     0.8445         1.46        1.0436     1.4598         1.40
8192           1.5382     2.2368         1.45        2.0536     3.0638         1.49        3.5930     5.2831         1.47
16384          4.5495     8.7861         1.93        8.0492    12.6046         1.57       12.5930    21.3581         1.70
32768         15.0513    39.1619         2.60       31.8396    49.9077         1.57       46.6913    88.4388         1.89
65536         59.2507        NaN          NaN      131.1242        NaN          NaN      189.8240        NaN          NaN

=== dtype=fp32  d=64 ===
         fwd_flash_ms  fwd_pt_ms  fwd_speedup  bwd_flash_ms  bwd_pt_ms  bwd_speedup  e2e_flash_ms  e2e_pt_ms  e2e_speedup
seq_len

## Toy Model

In [1]:
import torch
import torch.nn as nn


class ToyModel(nn.Module):
    def __init__(self, in_features, out_features):
        super().__init__()
        self.fc1 = nn.Linear(in_features, 10, bias=False)
        self.ln = nn.LayerNorm(10)
        self.fc2 = nn.Linear(10, out_features, bias=False)
        self.relu = nn.ReLU()

    def forward(self, x):
        print(f"fc1 weight dtype:     {self.fc1.weight.dtype}")
        x = self.relu(self.fc1(x))
        print(f"fc1 output dtype:     {x.dtype}")
        x = self.ln(x)
        print(f"layer norm output:    {x.dtype}")
        x = self.fc2(x)
        print(f"logits dtype:         {x.dtype}")
        return x


model = ToyModel(20, 5).cuda()
x = torch.randn(4, 20).cuda()

with torch.autocast(device_type="cuda", dtype=torch.float16):
    logits = model(x)
    loss = logits.sum()
    print(f"loss dtype:           {loss.dtype}")

loss.backward()
print(f"fc1 weight grad dtype: {model.fc1.weight.grad.dtype}")

fc1 weight dtype:     torch.float32
fc1 output dtype:     torch.float16
layer norm output:    torch.float32
logits dtype:         torch.float16
loss dtype:           torch.float32
fc1 weight grad dtype: torch.float32